:issue_tracker_url: https://github.com/jakartaee/faces/issues/



[appendix]
== Change Log

Note: this refers to historic issues and titles using the term "JSF". This refers to the
pre-Jakarta Faces specification under the JCP.

=== Changes between 4.1 and 4.0

This release contains the following changes:

* Issue ID {issue_tracker_url}1832[1832] +
Unify ActionSource and ActionSource2

* Issue ID {issue_tracker_url}1829[1829] +
Faces 4.1: Deprecate full state saving (FSS)

* Issue ID {issue_tracker_url}1828[1828] +
Remove mentions in javadoc wrt backwards compatibility of facelets.* context params

* Issue ID {issue_tracker_url}1823[1823] +
FacesMessage: implement equals(), hashcode(), toString()

* Issue ID {issue_tracker_url}1821[1821] +
Spec: jakarta.faces.FACELETS_REFRESH_PERIOD default when ProjectStage is Development

* Issue ID {issue_tracker_url}1819[1819] +
Add UUIDConverter

* Issue ID {issue_tracker_url}1811[1811] +
Missing "if" attribute of <f:viewAction>

* Issue ID {issue_tracker_url}1789[1789] +
Make FacesMessage#VALUES / VALUES_MAP generic

* Issue ID {issue_tracker_url}1764[1764] +
Add ExternalContext.setResponseContentLengthLong

* Issue ID {issue_tracker_url}1760[1760] +
id attribute is missing in vdl of h:head and h:body

* Issue ID {issue_tracker_url}1739[1739] +
Require firing events for @Initialized, @BeforeDestroyed, @Destroyed for build-in scopes.

* Issue ID {issue_tracker_url}1712[1712] +
Javadoc for Application.subscribeToEvent methods has a reference to context that is incorrect

* Issue ID {issue_tracker_url}1708[1708] +
Add missing generics to API that were missed in Faces 4.0

* Issue ID {issue_tracker_url}1707[1707] +
Deprecate unused PreDestroyCustomScopeEvent and PostConstructCustomScopeEvent

* Issue ID {issue_tracker_url}1549[1549] +
Deprecate unused composite:extension

* Issue ID {issue_tracker_url}1342[1342] +
Support @Inject of current flow like "@Inject Flow currentFlow"

* Issue ID {issue_tracker_url}1263[1263] +
Add rowStatePreserved property to UIRepeat, exactly the same as UIData

* Issue ID {issue_tracker_url}1864[1864] +
dataTable rowStatePreserved attribute is missing in vdl

This release now requires Java SE 17 or newer (aligned with Jakarta EE 11).


=== Changes between 4.0 and 3.0

This release contains the following changes:

* Issue ID {issue_tracker_url}1581[1581] +
New API to programmatically create Facelets

* Issue ID {issue_tracker_url}1508[1508] + 
New automatic extensionless mapping

* Issue ID {issue_tracker_url}1509[1509] +
New annotation @ClientWindowScoped

* Issue ID {issue_tracker_url}1570[1570] +
Support custom cookie attributes such as SameSite in ExternalContext#addResponseCookie()

* Issue ID {issue_tracker_url}1555[1555] +
New attribute &lt;h:inputFile multiple="...">

* Issue ID {issue_tracker_url}1556[1556] +
New attribute &lt;h:inputFile accept="...">

* Issue ID {issue_tracker_url}1557[1557] +
New method FacesContext#getLifecycle()

* Issue ID {issue_tracker_url}1559[1559] +
New tag &lt;f:selectItemGroups>

* Issue ID {issue_tracker_url}1560[1560] +
New attribute &lt;h:inputText type="...">

* Issue ID {issue_tracker_url}1563[1563] +
New tag &lt;f:selectItemGroup>

* Issue ID {issue_tracker_url}1568[1568] +
New method UIViewRoot#getDoctype()

* Issue ID {issue_tracker_url}1573[1573] +
New attribute &lt;f:websocket onerror="...">

* Issue ID {issue_tracker_url}1574[1574] +
New layout="list" for &lt;h:selectManyCheckbox> and &lt;h:selectOneRadio>

* Issue ID {issue_tracker_url}1582[1582] +
New annotation literals for all @Qualifiers

* Issue ID {issue_tracker_url}1558[1558] +
Make UIComponent#subscribeToEvent() more convenient

* Issue ID {issue_tracker_url}1565[1565] +
Skip type attribute from &lt;link> and &lt;script> when doctype is HTML5

* Issue ID {issue_tracker_url}1567[1567] +
Improve &lt;f:ajax> behavior in composite components

This release now requires Java SE 11 or newer (aligned with Jakarta EE 10).


==== Backward Compatibility with Previous Versions

This release contains the following backwards incompatible changes:

* Issue ID {issue_tracker_url}1552[1552] +
Rename "JSF" to "Faces" over all place

* Issue ID {issue_tracker_url}1553[1553] +
Rename "http://xmlns.jcp.org/jsf/*" URL to "jakarta.faces.*" URN

* Issue ID {issue_tracker_url}1546[1546] +
Remove all JSP support

* Issue ID {issue_tracker_url}1547[1547] +
Remove native Managed Beans (@ManagedBean and related)

* Issue ID {issue_tracker_url}1548[1548] +
Remove MethodBinding, ValueBinding and friends

* Issue ID {issue_tracker_url}1571[1571] +
Remove CURRENT_COMPONENT constants from UIComponent class

* Issue ID {issue_tracker_url}1578[1578] +
Remove deprecated methods of StateManager class

* Issue ID {issue_tracker_url}1583[1583] +
Remove entire ResourceResolver class


=== Changes between 3.0 and 2.3

Namespace has been changed from  `javax.faces` to `jakarta.faces`.

==== Backward Compatibility with Previous Versions

Jakarta Faces 3.0 has a breaking change due to the namespace change from  `javax.faces` to `jakarta.faces`.

=== Changes between 2.2 and 2.3

This section gives the reader a survey of the changes between version 2.3
of the specification and version 2.2, using the categories from the issue
tracker at {issue_tracker_url}.

==== Big Ticket Features

* WebSocket Integration +
Issue ID {issue_tracker_url}1396[1396] +
See the VDLDocs for <f:websocket>.

* Multi-field Validation +
Issue ID {issue_tracker_url}1[1] +
See the VDLDocs for <f:validateWholeBean>.

* Java Time Support +
Issue ID {issue_tracker_url}1370[1370] +
See the VDLDocs for <f:convertDateTime>.

// #a3070 Section 5.9.2 “EL Resolution”
* Use CDI for evaluation of JSF specific EL implicit Objects +
Issue ID
{issue_tracker_url}1311[1311],
{issue_tracker_url}1322[1322],
{issue_tracker_url}1325[1325],
{issue_tracker_url}1327[1327],
{issue_tracker_url}1328[1328],
{issue_tracker_url}1334[1334],
{issue_tracker_url}1332[1332],
{issue_tracker_url}1331[1331],
{issue_tracker_url}1384[1384],
{issue_tracker_url}1385[1385],
{issue_tracker_url}1383[1383],
{issue_tracker_url}1386[1386] - {issue_tracker_url}1394[1394] +
See <<ExpressionLanguageFacility.adoc#a3070>>

* Issue ID {issue_tracker_url}1417[1417] +
Deprecate javax.faces.bean. 

// #a3054 Section 5.9.1 “JSF Objects Valid for @Inject Injection”
* Support @Inject on JSF specific artifacts +
Issue ID
{issue_tracker_url}1316[1316],
{issue_tracker_url}527[527],
{issue_tracker_url}1309[1309],
{issue_tracker_url}1323[1323],
{issue_tracker_url}1283[1283],
{issue_tracker_url}1353[1353],
{issue_tracker_url}1335[1335],
{issue_tracker_url}1333[1333],
{issue_tracker_url}1349[1349],
{issue_tracker_url}1351[1351],
{issue_tracker_url}1350[1350],
{issue_tracker_url}1345[1345] +
See <<ExpressionLanguageFacility.adoc#a3054>>
 
* Issue ID {issue_tracker_url}1364[1364] +
UIData and <ui:repeat> supports Map and Iterable

* Issue ID {issue_tracker_url}1102[1102] +
ui:repeat condition check. +

* Issue ID {issue_tracker_url}1418[1418] +
CDI Replacement for @ManagedProperty. +
See javadocs for javax.faces.annotation.ManagedProperty.

* Issue ID {issue_tracker_url}1103[1103], {issue_tracker_url}1364[1364] +
See the Javadoc for javax.faces.component.UIData,
and javax.faces.model.IterableDataModel.

* DataModel implementations can be registered +
Issue ID {issue_tracker_url}1078[1078] +
See the javadoc for annotation javax.faces.model.FacesDataModel.

* Issue ID {issue_tracker_url}1412[1412] +
See the javadoc for annotation
javax.faces.partialViewContext.getEvalScripts().

* Issue ID {issue_tracker_url}613[613] +
Ajax Method Invocation. See vdldoc for <h:commandScript>.

* Issue ID {issue_tracker_url}1238[1238] +
Enhanced component search facility.
See the javadoc for package javax.faces.component.search.


==== Other Features, by Functional Area

===== Components/Renderers

.Larger Changes

* Issue ID {issue_tracker_url}217[217] +
styleClass attribute added to h:column

* Issue ID {issue_tracker_url}329[329] +
Add “group” attribute to <h:selectOneRadio>.

* Issue ID {issue_tracker_url}1423[1423], {issue_tracker_url}1404[1404] +
ResourceHandler.markResourceRendered(), and isResourceRendered(),
UIViewRoot.getComponentResources() enable the discovery of
dynamically added resources, even within Ajax requests.

* Issue ID {issue_tracker_url}1404[1404] +
Add API to check if a resource has already been rendered.
See Javadoc for
javax.faces.application.ResourceHandler.markResourceRendered()
and isResourceRendered().

// #a457 Section 2.2.6 “Render Response”
* Issue ID {issue_tracker_url}1436[1436] +
In <<RequestProcessingLifecycle.adoc#a457>>,
specify how Server Push is utilized.

.Smaller Changes

* Issue ID {issue_tracker_url}1422[1422] +
UISelectMany detects converter based on first item.

* Issue ID {issue_tracker_url}1007[1007] +
Explicit support for dynamic component manipulation

* Issue ID {issue_tracker_url}819[819] +
Add “disabled” attribute for h:button

* Issue ID {issue_tracker_url}1300[1300] +
UIViewRoot.getViewMap() and publishEvent().

* Issue ID {issue_tracker_url}1229[1229] +
Document UIData.setRowStatePreserved() in VDLDoc and RenderKit Doc.

* Issue ID {issue_tracker_url}1135[1135] +
Add PostRenderViewEvent.

* Issue ID {issue_tracker_url}1258[1258] +
Clarify text escaping for <h:outputText> or equivalent EL expressions.

* Issue ID {issue_tracker_url}807[807] +
Pass FacesContext to system event listeners.

* Issue ID {issue_tracker_url}1113[1113] +
Remove onselect attribute from SELECT components.

* Issue ID {issue_tracker_url}1433[1433] +
Add a context-param to enable forcing validation to happen even when
there is no parameter corresponding to the current component.

===== Lifecycle

.Larger Changes

* Issue ID {issue_tracker_url}790[790] +
javax.faces.ViewState and ajax with cross form submit.

.Smaller Changes

* Issue ID {issue_tracker_url}473[473] +
FacesEvent.getFacesContext().

* Issue ID {issue_tracker_url}1241[1241] +
faces-config supports client-window-factory.

* Issue ID {issue_tracker_url}1346[1346] +
Simplify decoration of FaceletCacheFactory.

* Issue ID {issue_tracker_url}1361[1361] +
Correct oversight regarding re-entrancy of flow scoped beans.

* Issue ID {issue_tracker_url}821[821] +
Implement ExternalContext.getRealPath() on startup and shutdown.

* Issue ID {issue_tracker_url}1401[1401] +
Explicitly prohibit using NavigationHandler from within ExceptionHandler invoked during RENDER RESPONSE.

* Issue ID {issue_tracker_url}1306[1306] +
@FlowScoped should be @NormalScope(passivating=true).

* Issue ID {issue_tracker_url}1382[1382] +
Generify return from ExternalContext.getInitParameterMap().

* Issue ID {issue_tracker_url}1329[1329] +
@NotNull and <f:viewParam>.

* Issue ID {issue_tracker_url}1403[1403] +
Allow entry into flow via <f:viewAction>.

* Issue ID {issue_tracker_url}1216[1216] +
Improve consistency in handling PhaseListener instances
registered on UIViewRoot components.

* Issue ID {issue_tracker_url}1435[1435] +
Add ResourceHandler.getViewResources() method.

===== Platform Integration

* Issue ID {issue_tracker_url}1379[1379] +
ExternalContext.getResponseCharacterEncoding() and Portlet 3.0.

===== Facelets/VDL

.Larger Changes

* Issue ID {issue_tracker_url}1424[1424] +
Add tag <f:importConstants>, see VDLDoc for that tag.

.Smaller Changes

* Issue ID {issue_tracker_url}1362[1362] +
Revisit some cardinality rules regarding <tag> and <component> elements.

* Issue ID {issue_tracker_url}936[936] +
Set FACELETS_REFRESH_PERIOD to -1 if ProjectStage is Production.

===== Spec Clarifications

* Issue ID {issue_tracker_url}1254[1254] +
Loosen language regarding the contracts attribute on <f:view>.

* Issue ID {issue_tracker_url}1338[1338] +
Clarify pseudocode for resource libraries.

* Issue ID {issue_tracker_url}1279[1279] +
Specify UIInput.isEmpty()

* Issue ID {issue_tracker_url}1242[1242] +
Remove mentione of OpenAjax hub.

* Issue ID {issue_tracker_url}1215[1215] +
Additional warning on DelegatingMetaTagHandler.getTagHandlerDelegate.

* Issue ID {issue_tracker_url}1131[1131] +
“name” attribute not required.

* Issue ID {issue_tracker_url}1270[1270] +
TagDecorator spec namespace modifications.

* Issue ID {issue_tracker_url}1401[1401] +
Advisory text for ExceptionHandler.

* Issue ID {issue_tracker_url}1402[1402] +
Explicitly declare that flow eagerness not supported.

* Issue ID {issue_tracker_url}677[677] +
Document automatic UIPanel behavior for f:facet.

* Issue ID {issue_tracker_url}1095[1095] +
Description for “rendered” attribute for repeat and fragment.

* Issue ID {issue_tracker_url}1066[1066] +
Application.getNavigationHandler() and application element.

* Issue ID {issue_tracker_url}803[803] +
VisitHint.EXECUTE_LIFECYCLE clarifications.

* Issue ID {issue_tracker_url}1217[1217] +
EnumConverter.getAsString() clarifications.

* Issue ID {issue_tracker_url}1356[1356] +
UIInput.processValidators() clarifications.

* Issue ID {issue_tracker_url}1424[1424] +
Public constants for source, behavior, and partial.event.
See the Javadocs for
javax.faces.component.behavior.ClientBehaviorContext, and javax.faces.conetxt.PartialViewContext.

* Issue ID {issue_tracker_url}1428[1428] +
API constants for jsf.js and javax.faces in JavaScript.

// #a3913 Section 7.6.2.1 “ViewHandler Methods that Derive Information From the Incoming Request”
// #a3955 Section 7.6.2.3 “ViewHandler Methods Relating to Navigation”
* Issue ID {issue_tracker_url}1260[1260] +
Support for exact mapping of FacesServlet.
See <<ApplicationIntegration.adoc#a3913>>
and <<ApplicationIntegration.adoc#a3955>>.

// #a2541 TABLE 5-3 “JSF Artifacts Eligible for Injection”
Issue ID {issue_tracker_url}1250[1250] +
Fix entries in table
<<ExpressionLanguageFacility.adoc#a2541>>.

===== Resources

.Larger Changes

.Smaller Changes

===== Expression Language


===== Configuration and Bootstrapping


===== Miscellaneous

// #a554 Section 2.5.2.1 “Determining the active Locale”
* Issue ID {issue_tracker_url}1225[1225] +
Clarify requirements to support BCP-47 regarding localization.
See <<RequestProcessingLifecycle.adoc#a554>>

* Issue ID {issue_tracker_url}1429[1429] +
Add constructor to make wrapping easier.

* Issue ID {issue_tracker_url}1430[1430] +
Leverage Java SE 8 repeatable annotations where appropriate.


==== Backward Compatibility with Previous Versions

// #a6088 Section 11.1.3 “Application Configuration Parameters”
JSF 2.3 is fully backward compatible with previous releases of JSF,
unless any of the following context-parameter values are specified.
See <<UsingFacesInWebApplications.adoc#a6088>> for details.

[none]
* javax.faces.ALWAYS_PERFORM_VALIDATION_WHEN_REQUIRED_IS_TRUE

* javax.faces.DISABLE_FACESSERVLET_TO_XHTML

* javax.faces.VIEWROOT_PHASE_LISTENER_QUEUES_EXCEPTIONS.

JSF 2.3 is fully backward compatible with previous releases of JSF
unless a CDI managed bean is included in the application
with the annotation @javax.faces.annotation.FacesConfig.
See the javadocs for that annotation for details.



==== Breakages in Backward Compatibility



=== Changes between 2.1 and 2.2

This section gives the reader a survey of the
changes between this version of the specification and the previous
version, using the categories from the issue tracker at <
{issue_tracker_url} >.

==== Big Ticket Features

* HTML5 Friendly Markup +
Issue ID {issue_tracker_url}1090[1090] +
Start with
<<FaceletsAndWebApplications.adoc#a5581,HTML5 Friendly Markup>>

* Resource Library Contracts +
Issue ID {issue_tracker_url}1142[1142] +
Start with <<FaceletsAndWebApplications.adoc#a5526,
Resource Library Contracts Background>>.

* Faces Flows +
Issue ID {issue_tracker_url}730[730] +
Start with <<ApplicationIntegration.adoc#a3840,
FlowHandler>>.

* Stateless Views +
Issue ID {issue_tracker_url}1055[1055] +
Start with <<ApplicationIntegration.adoc#a4126,
Stateless Views>>.

==== Other Features, by Functional Area

===== Components/Renderers

.Larger Changes

* Issue ID {issue_tracker_url}479[479] +
UIData supports the Collection Interface rather than List.

* Issue ID {issue_tracker_url}1134[1134] +
Add the "role" pass through attribute.

.Smaller Changes

* Issue ID {issue_tracker_url}1080[1080] +
Warn about some important corner cases when
_UIComponent.findComponent()_ may not provide the expected results.

* Issue ID {issue_tracker_url}1068[1068] +
New section describing what happens with
respect to partial processing during render response. See
<<RequestProcessingLifecycle.adoc#a480,Render Response Partial Processing>>.

* Issue ID {issue_tracker_url}1067[1067] +
Spec clarifications. See the VDLDoc for __cc:insertChildren__,
_cc:insertFacet_

* Issue ID {issue_tracker_url}1061[1061] +
Clarify that both
_Application.publishEvent()_ and the manual traversal based delivery are
required for publishing the __PostRestoreStateEvent__.

* Issue ID {issue_tracker_url}1030[1030] +
Clarify docs for h:message h:messages

* Issue ID {issue_tracker_url}1023[1023] +
Modify JavaDoc to relax requirements for PostAddToViewEvent publishing

* Issue ID {issue_tracker_url}1019[1019] +
Modify spec for ResponseWriter.writeURIAttribute() to explicitly require
adherence to the W3C URI spec

* Issue ID {issue_tracker_url}997[997] +
javax.faces.component.ComponentSystemEvent: Override
isAppropriateListener so that it first asks the listener, "are you a
ComponentSystemEventListener", then, if not, asks
super.isAppropriateListener()

* Issue ID {issue_tracker_url}984[984] +
Component Context Manager, see
__javax.faces.component.visit.ComponentModificationManager__.

* Issue ID {issue_tracker_url}943[943] +
See _javax.faces.view.ViewDeclarationLanguageWrapper_

* Issue ID {issue_tracker_url}784[784] +
Deprecate the CURRENT_COMPONENT and CURRENT_COMPOSITE_COMPONENT
attributes

* Issue ID {issue_tracker_url}599[599] +
Make it possible to programmatically create components in the same way
as they are created by Facelets. See
_javax.faces.application.Application.createComponent(FacesContext,
String taglibUri, String tagName, Map attrs)_

* Issue ID {issue_tracker_url}703[703] +
Make "value" optional for @FacesComponent.

* Issue ID {issue_tracker_url}585[585] +
outputText and inputText do not render children by default

* Issue ID {issue_tracker_url}550[550] +
OutputStylesheet "media" attribute

* Issue ID {issue_tracker_url}1125[1125] +
_javax.faces.application.Application_ event subscription clarifications.

===== Lifecycle

.Larger Changes

* Issue ID {issue_tracker_url}949[949], {issue_tracker_url}947[947] +
Give JSF the ability to correctly handle browsing context (tab, browser
window, pop-up, etc). See __javax.faces.lifecycle.ClientWindow__.

* Issue ID {issue_tracker_url}758[758] and {issue_tracker_url}1042[1042]
+
A jsf-api/src/main/java/javax/faces/component/UIViewAction.java
+
--
[none]
* The heart of this changebundle, this class
came over from the JBoss Seam Faces Module, but I've rewritten most of
the javadoc.
--
+
M jsf-api/src/main/java/javax/faces/event/PhaseId.java
+
--
[none]
* new methods

* public String getName()

* public static PhaseId phaseIdValueOf(String
phase)
--
+
Change <<ApplicationIntegration.adoc#a3571,
Default NavigationHandler Algorithm>> to account for UIViewAction

* Issue ID {issue_tracker_url}1062[1062] and {issue_tracker_url}802[802] +
File Upload

* Issue ID {issue_tracker_url}766[766] +
Events from the flash

* Issue ID {issue_tracker_url}1050[1050] +
Add support for delay value in options for Ajax requests

.Smaller Changes

* Issue ID {issue_tracker_url}1129[1129] +
In validate(), clarify that setSubmittedValue() null must be called if
validation succeeds.

* Issue ID {issue_tracker_url}1071[1071]
Add FlashFactory. See
<<UsingFacesInWebApplications.adoc#a6336,Delegating Implementation Support>>.

* Issue ID {issue_tracker_url}1065[1065] +
When calculating the locale for the
resource library prefix, if there is a UIViewRoot, use its locale first,
otherwise, just use the Applications’s ViewHandler’s calculateLocale()
method. See <<RequestProcessingLifecycle.adoc#a836,Libraries of Localized and
Versioned Resources>>

* Issue ID {issue_tracker_url}1039[1039] +
In ApplicationWrapper, mark things as deprecated

* Issue ID {issue_tracker_url}1028[1028] +
Deprecate StateManager, point to StateManagementStrategy. In
StateManagementStrategy, require the use of the visit API to perform the
saving.

* Issue ID {issue_tracker_url}993[993] +
Wrapper for ActionListener

* Tweak circumstances for skipping intervening
lifecycle phases in the case of view metadata
Issue ID {issue_tracker_url}762[762]
+
Section 2.2.1. Now has this text.
+
--
[none]
* Otherwise, call getViewMetadata() on the
ViewDeclarationLanguage instance. If the result is non-null, call
createMetadataView() on the ViewMetadata instance. Call
ViewMetadata.getViewParameters(). If the result is a non-empty
Collection, do not call facesContext.renderResponse(). If the result is
an empty collection, try to obtain the metadata facet of the UIViewRoot
by asking the UIViewRoot for the facet named
UIViewRoot.METADATA_FACET_NAME. This facet must exist. If the facet has
no children, call facesContext.renderResponse(). Otherwise, none of the
previous steps have yielded the discovery any of metadata, so call
facesContext.renderResponse().
--

* Issue ID {issue_tracker_url}566[566] +
UIOutput.getValue() value returns.

* Issue ID {issue_tracker_url}220[220] +
In web-partialresponse_2_2.xsd, require that
the <partial-response> element has an “id” attribute whose value is the
return from __UIViewRoot.getContainerClientId()__.



===== Platform Integration

* Issue ID {issue_tracker_url}763[763] +
Change 
Managed Bean Annotations to account for new injectability requirements.

* Issue ID {issue_tracker_url}976[976] +
In Javadoc for “Faces Managed Bean Annotation Specification For
Containers Conforming to Servlet 2.5 and Beyond”, indicate that
_javax.faces.bean_ will be deprecated in the next version.

* Issue ID {issue_tracker_url}1087[1087] +
Introduce CDI based @ViewScoped annotation.

===== Facelets/VDL

.Larger Changes

* Issue ID {issue_tracker_url}1001[1001] +
Allow cc and non-cc components in one taglib
+
A jsf-api/doc/web-facelettaglibrary_2_2.xsd
+
First change to the facelet taglib schema in
2.2: introduce the ability to declare a resource which will be the
composite component for a tag. Now, before you get all excited about
what conventions we can use to make this easier, let me stop you right
there. Here is a summary of the ease of use story regarding taglib
files.
+
--
[none]
* The 80/20 rule says we should make taglib
files optional most of the time. Here are the 80% cases.

* Employs the cc naming convention
\http://java.sun.com/jsf/composite/<libraryName>

* The user employs a java component has a
@FacesComponent on it that declares the necessary metadata.
Issue ID {issue_tracker_url}594[594]
--
+
Here are some of the cases where you must
have a taglib file, the 20% cases.
+
--
[none]
* If you want to employ a cc with a namespace
other than \http://java.sun.com/jsf/composite/<libraryName> you need to
have a taglib file that declares <composite-library-name>. Currently you
must not detlare any <tag> elements in such a taglib file. All the tags
in such a library must come from the same resource library.

* If the user is not employs a java component
but is not using @FacesComponent.
--
+
This patch introduces the following syntax.
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<facelet-taglib xmlns="http://java.sun.com/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
    http://java.sun.com/xml/ns/javaee/web-facelettaglibary_2_2.xsd"
    version="2.2">
  <namespace>test</namespace>
  <tag>
    <tag-name>layout</tag-name>
    <resource-id>myCC/whatever.xhtml</resource-id>
  </tag>
</facelet-taglib>
----
+
Where _<resource-id>_ is a valid resource
identifier as specified in section 2.6.1.3.

* Issue ID {issue_tracker_url}548[548] +
Require additional check to handle the case
where, in one resource library, there are both localized and
non-localized resources. See <<RequestProcessingLifecycle.adoc#a836,Libraries
of Localized and Versioned Resources>>.

.Smaller Changes

* Issue ID {issue_tracker_url}1038[1038] +
Declare an annotation corresponding to the
_javax.faces.FACELETS_RESOURCE_RESOLVER_ application configuration
parameter. See <<UsingFacesInWebApplications.adoc#a6598,Requirements for scanning
of classes for annotations>> and <<UsingFacesInWebApplications.adoc#a6088,
Application Configuration Parameters>>.

* Issue ID {issue_tracker_url}1082[1082] +
Account for DOCTYPE discrepancy between
server side representation of Facelet VDL files, which are proper XHTML,
and processed files which are sent to the client, which now, by default,
are HTML5 HTML syntax files. See <<FacesMetadata.adoc#a7061,The
facelets-processing element>>.

* Fix incorrect VDLDoc
Issue ID {issue_tracker_url}967[967]
f:selectItems itemValue description incorrect.

* Issue ID {issue_tracker_url}922[922] +
Remove maxlength from f:viewParam

* Issue ID {issue_tracker_url}998[998] +
Document that ui:fragment should not be bound to a bean with wider than
request scope, document that the type of the property must extend from
UIComponent.

* Issue ID {issue_tracker_url}999[999] +
Changes to "template" attribute requiredness for ui:decorate and
ui:composition

* Issue ID {issue_tracker_url}901[901] +
Deprecate “targets” concept.

* Issue ID {issue_tracker_url}1088[1088] +
add short-name to schema.

* Issue ID {issue_tracker_url}746[746] +
Missing _method-signature_ element in taglib xsd.

===== Spec Clarifications

* Issue ID {issue_tracker_url}1136[1136] +
In __ExternalContext.dispatch()__, clarify what is to be done if
_getRequestDispatcher()_ returns __null__.

* Issue ID {issue_tracker_url}1132[1132] +
Replace literal strings with symbolic constants where possible.

* Issue ID {issue_tracker_url}1127[1127] +
State Saving Serializability concerns.

* Issue ID {issue_tracker_url}1114[1114] +
_javax.faces.view.facelets.Facelet.apply()_ spec version reference
error.

* Issue ID {issue_tracker_url}1100[1100], {issue_tracker_url}1097[1097] +
HTML5 id attribute sensitivity

* Issue ID {issue_tracker_url}1064[1064] +
In <<JSFMetadata.adoc#a7061,The
facelets-processing element>>, clarify that in XML and JSPX modes, only
the CDATA section start and end tags, not the entire CDATA section and
contents, should be consumed.

* Issue ID {issue_tracker_url}1063[1063] +
_javax.faces.component.UIViewParameter.getSubmittedValue()_ return
value.

* Issue ID {issue_tracker_url}1058[1058] +
ui:repeat tag size attribute

* Issue ID {issue_tracker_url}1036[1036] +
In <<UserInterfaceComponentModel.adoc#a911,
ValueExpression properties>>, clarify which attributes are expression
enabled,

* Issue ID {issue_tracker_url}1035[1035] +
Change section
<<Per-RequestStateInformation.adoc#a3300,FacesMessage>> to clarify the meaning of
having _FacesMessage_ instances on the _FacesContext._

* Issue ID {issue_tracker_url}1026[1026] +
f:ajax event attribute is String (not VE)

* Issue ID {issue_tracker_url}1014[1014]
+
12.1.3
+
--
[none]
* The specification for the context-param that
declares the list of TagDecorator implementations to the runtime should
have always been javax.faces.FACELETS_DECORATORS. Prior to this
revision, the name of this context param was incorrectly specified as
javax.faces.DECORATORS. The reference implementation has always used the
correct name, however.
--

* Issue ID {issue_tracker_url}1010[1010] +
Check existing usages of the state saving method parameter to ensure
case insensitivity.

* Issue ID {issue_tracker_url}1004[1004]
+
M usingFacesInWebapps.fm
+
--
[none]
* 12.1.3 Set default for
javax.faces.FACELETS_BUFFER_SIZE to be 1024.
--

* Issue ID {issue_tracker_url}998[998] +
Additional clarification about binding attribute in VDLDocs

* Issue ID {issue_tracker_url}915[915], {issue_tracker_url}1015[1015] +
Non-normative text about http methods and prefix mapping

* Issue ID {issue_tracker_url}2740[2740] +
In <<UserInterfaceComponentModel.adoc#a923,Component Bindings>>, clarify a corner
case regarding bean scope and component binding.

===== Resources

.Larger Changes

* Issue ID {issue_tracker_url}809[809] +
This commit introduces a cleaner contract for allowing views to be
loaded from the Filesystem (including inside of JAR files). All VDL
resources must be loaded using ResourceHandler.createViewResource().

.Smaller Changes

* Issue ID {issue_tracker_url}996[996] +
Enable configuring the web app resources
directory. See <<UsingFacesInWebApplications.adoc#a6088,Application Configuration
Parameters>>.

* Issue ID {issue_tracker_url}719[719] +
Method to map a viewId to a resourcePath

* Issue ID {issue_tracker_url}1130[1130] +
Modify <<ApplicationIntegration.adoc#a4135,State Saving Alternatives and
Implications>> to clarify there is no requirement to serialize server
state by default when state saving method is server. Introduce a context
parameter to this effect in <<UsingFacesInWebApplications.adoc#a6088,Application
Configuration Parameters>>

===== Expression Language

* Issue ID {issue_tracker_url}1092[1092]
+
Remove text from
MethodExpressionValueChangeListener and MethodExpressionActionListener
regarding wrapping any exception thrown by the invoked method being
wrapped in an AbortProcessingException. Such a requirement is incorrect
and should not have been introduced.
+
In section <<Per-RequestStateInformation.adoc#a3253,
ExceptionHandler>>, add __AbortProcessingException__, to the list of
exceptions that do not get to the __ExceptionHandler__.

* Issue ID {issue_tracker_url}1043[1043] +
When publishing a ComponentSystemEvent, ensure the EL current component
is pushed correctly

* Issue ID {issue_tracker_url}1164[1164] +
If running in a container that supports EL 3.0, add the necessary
ELResolvers. See <<ExpressionLanguageFacility.adoc#a2966,Stream, StaticField,
Map, List, Array, and Bean ELResolvers>>.

===== Configuration and Bootstrapping

* Issue ID {issue_tracker_url}533[533] +
Modify <<UsingFacesInWebApplications.adoc#a6201,
Application Startup Behavior>> to account for requirement to call new API
when starting up.

===== Miscellaneous

* Issue ID {issue_tracker_url}1169[1169]
+
New XML Namespace for XSD files introduced in
JSF 2.2, and also for facelet tag libraries.
+
The following XSD files are new for JSF 2.2,
and each will be in the XML namespace
__http://xmlns.jcp.org/xml/ns/javaee__.
+
--
[none]
* _web-facelettaglibrary_2_2.xsd_

* _web-facesconfig_2_2.xsd_

* _web-partialresponse_2_2.xsd_
--
+
Facelet Tag Libraries will now respond to the
following URIs
+
--
[width="100%",cols="24%,38%,38%",options="header",]
|===
|Library |Old URI
|New URI
|Composite Components
|http://java.sun.com/jsf/composite a|
http://xmlns.jcp.org/jsf/composite



|Faces Core
|http://java.sun.com/jsf/core a|
http://xmlns.jcp.org/jsf/core



|HTML_BASIC
|http://java.sun.com/jsf/html a|
http://xmlns.jcp.org/jsf/html



|JSTL Core a|
http://java.sun.com/jsp/jstl/core



a|
http://xmlns.jcp.org/jsp/jstl/core



|JSTL Functions
|http://java.sun.com/jsp/jstl/functions a|
http://xmlns.jcp.org/jsp/jstl/functions



|Facelets Templating
|http://java.sun.com/jsf/facelets a|
http://xmlns.jcp.org/jsf/facelets



|Pass Through Attributes
|http://java.sun.com/jsf/passthrough a|
http://xmlns.jcp.org/jsf/passthrough



|Pass Through Elements
|http://java.sun.com/jsf a|
http://xmlns.jcp.org/jsf



|===
--
+
Developers are requested to use the values
from the New URI column, though both columns will work.

* Issue ID {issue_tracker_url}997[997]
+
M jsf-api/src/main/java/javax/faces/event/ComponentSystemEvent.java
+
--
[none]
* Override isAppropriateListener so that it
first asks the listener, "are you a ComponentSystemEventListener", then,
if not, asks super.isAppropriateListener()
--
+
M jsf-api/src/main/java/javax/faces/event/SystemEvent.java
+
--
[none]
* in isAppropriateListener(), document the
default implementation.
--
+
M jsf-api/src/main/java/javax/faces/component/UIComponent.java
+
--
[none]
* Make inner class
ComponentSystemEventListenerAdapter implement
ComponentSystemEventListener.
--

* Issue ID {issue_tracker_url}917[917]
+
javax.faces.application.ResourceWrapper:
+
--
[none]
* getContentType()

* getLibraryName()

* getResourceName()

* setContentType(String)

* setLibraryName(String)

* setResourceName(String)
--
+
javax.faces.context.ExternalContextWrapper:
+
--
[none]
* getSessionMaxInactiveInterval()

* isSecure()

* setSessionMaxInactiveInterval()
--
+
javax.faces.context.PartialViewContextWrapper
+
--
[none]
* setPartialRequest(boolean)
--

* 12.1.3 add this text to the
javax.faces.STATE_SAVING_METHOD spec. When examining the value, the
runtime must ignore the case.

* Add
ExternalContext.getApplicationContextPath()
Issue ID {issue_tracker_url}1012[1012]

* Issue ID {issue_tracker_url}787[787] +
restore ViewScope before templates are processed with buildView()

* 7.6.2.6 typo in spec for renderView(). Should be +
Return immediately if calling isRendered() on
the argument UIViewRoot returns false.

* Per Matt Benson, remove duplicate
descriptions of the cc and component implicit object from the getValue()
specification for the composite component ELResolver in section 5.6.2.1.

* Issue ID {issue_tracker_url}869[869]
+
Specify Cross Site Request Forgery
protection.
+
Add text in <<RequestProcessingLifecycle.adoc#a404,
Restore View>> to describe how non-postback requests are inspected for
protection, if necessary.
+
Remove text for writeState() in
<<RenderingModel.adoc#a4288,ResponseStateManager>>, point to the
JavaDocs.
+
Add View Protection methods to
<<ApplicationIntegration.adoc#a3874,Overview>> for ViewHandler.
+
Introduce subsections to
<<ApplicationIntegration.adoc#a3910,Default ViewHandler Implementation>> that
group the methods by their purpose. Add a new section
<<ApplicationIntegration.adoc#a3997,ViewHandler Methods that relate to View
Protection>>, which points to the javadocs. In
<<ApplicationIntegration.adoc#a3955,ViewHandler Methods Relating to
Navigation>>, in the spec for __getActionUrl()__, specify how view
protection is affected.

* Remove tables in section
<<UsingFacesInWebApplications.adoc#a6598,Requirements for scanning of classes for
annotations>> +
The Javadoc tool lists annotations in a
separate section, making the tables that list JSF related annotations
redundant.

* Issue ID {issue_tracker_url}1082[1082] +
Add new section
<<FaceletsAndWebApplications.adoc#a5635,DOCTYPE and XML Declaration>>.

* Issue ID {issue_tracker_url}1141[1141] +
In <<RequestProcessingLifecycle.adoc#a758,Resource
Identifiers>>, declare that resourceName and resourceVersion, in addition
to the already listed other segments, are subject to the same
constraints.

* Issue ID {issue_tracker_url}1129[1129] +
In <<RequestProcessingLifecycle.adoc#a480,Render
Response Partial Processing>>, require calling _UIViewRoot.resetValues()_
if necessary.

==== Backward Compatibility with Previous Versions

Faces 2.2 is backwards compatible with Faces
2.1 and 2.0. This means that a web-application that was developed to run
with Faces 2.1 or 2.0 won’t require any modification when run with Faces
2.2 except in the cases described in the following section.

==== Breakages in Backward Compatibility

* Issue ID {issue_tracker_url}1092[1092] +
Due to an error in previous versions of the
specification, exceptions were silently being swallowed that now will
bubble up to the exception handler. Code that was relying on this
incorrect behavior may need to be modified to account for fixing this
problem.

* Issue ID {issue_tracker_url}745[745]
+
5.6.2.2 Table 5-11. Make the following
changes to the spec for Composite Component Attribute ELResoler
+
--
[none]
* Modify getType() according to new
specification language.

* Require the implementation of containsKey()
on the Map.

** containsKey(): If the attributes map contains
the key, return true. Otherwise, if a default value has been declared
for the attribute, return true. Otherwise, return false.
--
+
<<UserInterfaceComponentModel.adoc#a1671,
Composite Component Metadata>>
+
New text dealing with <cc:attribute>
+
--
[none]
* Any additional attributes on
_<cc:attribute/ >_ are exposed as attributes accessible from the
_getValue()_ and _attributeNames()_ methods on __PropertyDescriptor__.
The return type from getValue() must be a _ValueExpression_ with the
exception of the __getValue("type")__. The return type from
_getValue("type")_ must be __Class__. If the value specified for the
_type_ attribute of _<cc:attribute/>_ cannot be converted to an actual
__Class__, a _TagAttributeException_ must be thrown, including the _Tag_
and _TagAttribute_ instances in the constructor.
--

Yes, this is a backwards incompatible change,
but because the usecase is so specific, and the performance benefit so
substantial, it was judged to be worth the cost.




=== Changes between 2.0 Rev a and 2.1

==== <<FaceletsAndWebApplications.adoc#a5638,Facelet Tag Library mechanism>>

Document that the unprefixed namespace must
pass through.

==== New feature: <facelets-processing>

See <<FacesMetadata.adoc#a7040,
Required Handling of *-extension elements in the application
configuration resources files>>

==== Update schema for 2.1

The only new element is
<facelet-cache-factory>. See the full schema in the Javadoc section of
the documents.

==== Change Restore View Phase

Change <<RequestProcessingLifecycle.adoc#a404,
Restore View>> to require a call to _ViewHandler.deriveLogicalViewId()_
before trying to find the __ViewDeclarationLanguage__.

==== <<ApplicationIntegration.adoc#a3910,Default ViewHandler Implementation>>

Document _deriveLogicalViewId()._


=== Changes between 2.0 Final and 2.0 Rev a

==== Global changes

===== ExceptionQueuedEvent

The specification incorrectly refers to the
ExceptionQueuedEvent as the ExceptionEvent. All instances should be
replaced, as there is no such class ExceptionEvent in JSF.

===== Usage of the term "page" in the JSF 2.0 spec

This might be kind of nit-picky, but there
are several occurrences of the term "Facelet page" in the JSF 2.0 spec,
but I'd like to set forth the argument that the term "Facelet document"
or "Facelet view" would be more appropriate, depending on context.
Similarly, the spec uses the term "Composite component markup page"
which isn't always appropriate either. Better to call it a "Composite
component markup document" or something like that.

All Facelet XHTML files are documents, but
not all Facelet XHTML files are pages. There is a built-in bias to the
word "page" that assumes the markup output will be rendered as a "web
page" which is not always the case. In the case of portlets, the
rendered output is a fragment of markup (normally a <div>...</div>). In
the case of a custom renderkit, the rendered output might be some mobile
device. In the case of ICEfaces, the rendered markup is a server-side
DOM tree. In the case of a composite component, a Facelet XHTML file is
not a page, but a "Composite Component markup document" (or definition)
file.

For example.. Instead of a "Facelet Page", I
think the following should be called a "Facelet Document" or a "Facelet
View" (since the f:view tag is optional, but implied)

[source,xml]
----
<!DOCTYPE html>
<html xmlns:f="jakarta.faces.core"
      xmlns:h="jakarta.faces.html">
  <h:head>
    ...
  </h:head>
  <h:body>
    ...
  </h:body>
</html>
----

But in the case of Portlets, the <html> ,
<head>, and <body> tags are forbidden. The equivalent "Facelet Document"
or "Facelet View" for portlets would look like this:

[source,xml]
----
<f:view xmlns:f="jakarta.faces.core"
        xmlns:h="jakarta.faces.html">
  ...
</f:view>
----

==== Front Matter

Change Sun logo to Oracle Logo. Sun postal
address to Oracle postal address, and Sun phone number to Oracle phone
number

Update spec license.

==== Chapter 2

===== <<RequestProcessingLifecycle.adoc#a404,Restore View>>

Per Andy Schwartz recommendation, loosen the
spec requirements for the delivery of the PostRestoreStateEvent to be
"somewhere during RestoreView".

===== <<RequestProcessingLifecycle.adoc#a584,Localized Application Messages>>

Suggestion: Change to

Validation Error: Length is less than
allowable minimum of 5.

===== <<RequestProcessingLifecycle.adoc#a710,JSR 303 Bean Validation>>

Change "leas" to "least"

===== <<RequestProcessingLifecycle.adoc#a710,JSR 303 Bean Validation>> needs to reference "Bean Validation Integration" section

While reading section 2.5.7, one becomes very
disappointed with the limited about of information that it provides. But
section 3.5.6 provides more information, so the recommendation is that
these sections reference each other, or perhaps are combined in some way
if that makes sense.

===== <<RequestProcessingLifecycle.adoc#a758,Resource Identifiers>>

Tighten spec for the localePrefix,
libraryName, and resourceVersion segments of the resource identifier.

==== Chapter 3

===== Clarify meaning of "javax.faces.bean" in <<UserInterfaceComponentModel.adoc#a1464,Bean Validator Activation>>

Section 3.5.6.1 says:

"If Bean Validation is present in the runtime
environment, the system must ensure that the javax.faces.Bean standard
validator is added with a call to Application.addDefaultValidatorId()"

But the reader of the Spec has no idea what
the "javax.faces.Bean" standard validator is, within the context of this
paragraph. Recommend adding some verbiage that says that
javax.faces.Bean is the validatorId of the standard JSR 303 validator of
the JSF 2.0 API, which equates to the
javax.faces.validator.BeanValidator class as mentioned in Section
10.4.1.4.

===== Need to be consistent between <<UserInterfaceComponentModel.adoc#a1393,Declarative Listener Registration>> of the JSF 2.0 Spec and the VDLDoc for f:event

Section 3.4.3.4 of the JSF 2.0 Spec reads:

The method signature for the MethodExpression
pointed to by the listener attribute must match the signature of

javax.faces.event.ComponentSystemEventListener.processEvent().

And the VDLDocs for f:event read:

(signature must match public void
listener(javax.faces.event.ComponentSystemEvent event) throws
javax.faces.event.AbortProcessingException)

Both of these are true, and indeed saying the
same thing. But I think it would be helpful to say BOTH things, in BOTH
documents.

===== Typo in <<UserInterfaceComponentModel.adoc#a1393,Declarative Listener Registration>> of the JSF 2.0 Spec regarding "beforeRender"

Section 3.4.3.4 of the JSF 2.0 Spec has this
example:

[source,xml]
----
<h:inputText value="#{myBean.text}">
  <f:event type="beforeRender" listener="#{myBean.beforeTextRender}" />
</h:inputText>
----

But "beforeRender" is a typo. The correct
value is "preRenderComponent" as stated in the f:event VDLDocs.

===== <<UserInterfaceComponentModel.adoc#a1419,Validation Registration>>, <<UserInterfaceComponentModel.adoc#a1518,What does it mean to be a JSF User Interface component?>>

Remove references to UInput.encodeEnd(). Not
for a very long time has this method been used to instigate validation.

===== <<UserInterfaceComponentModel.adoc#a1671,Composite Component Metadata>>

Section 3.6.2.1 of the Spec indicates that
the "hidden" property of the javax.bean.FeatureDescriptor is to appear
as an attribute for tags like cc:actionSource,
cc:attribute, cc:facet, and cc:interface but the
VDLDocs do not declare that the "hidden" property is available.

==== Chapter 4

===== <<StandardUserInterfaceComponents.adoc#a2268,Events>>

Remove text pertaining to
PostRestoreStateEvent, rely instead on text in setion 2.2.1.

==== Chapter 7

===== <<ApplicationIntegration.adoc#a3562,Overview>>

getNavigationCase should return
NavigationCase and not void.

===== <<ApplicationIntegration.adoc#a3571,Default NavigationHandler Algorithm>>

Add faces-include-view-params

===== <<ApplicationIntegration.adoc#a3910,Default ViewHandler Implementation>>

Fix typo the specified createView() should be
called in renderView() and restoreView().

==== Chapter 10

Need to change "confirm with" to "conform
with".

Confusing verbiage in table 10-1 of JSF 2.0
spec regarding the word "template"

In table 10-1, it correctly says that "page
templating" is not a feature of JSP.

But later on in the table, it says
"Expressions in template text cause unexpected behavior when used in
JSP."

Somehow there needs to be an explanation of
the distinction of "page templating" and "template text" here. Right now
it kind of reads as a contradiction.

===== <<FaceletsAndWebApplications.adoc#a5632,General Requirements>>

Add an assertion to section 10.3.1 stating
that EL expressions that appear in the facelet XHTML page must appear in
the rendered view as if they were the right hand side of the value
attribute of an at the same point in the page as the EL expression

===== <<FaceletsAndWebApplications.adoc#a5638,Facelet Tag Library mechanism>>

Section 10.3.2. Correct xref to point to
section in appendix that includes the facelet taglib schema.

Correct xref to point to section in appendix
that includes the facelet taglib schema.

===== VDLDocs

See <<FaceletsAndWebApplications.adoc#a6043,Facelet Templating Tag Library>>,
and <<FaceletsAndWebApplications.adoc#a6047,Jakarta Tags Core and Function Tag Libraries>>.
Refer the reader to the "VDLDocs" (View Declaration Language Documentations).


==== Chapter 13

===== Redundancy in <<AjaxIntegration.adoc#a6831,Partial View Processing>> of the JSF 2.0 Spec

Section 13.4.2 of the JSF 2.0 spec has this
sentence:

The request contains special parameters that
indicate the request is a partial execute request or a partial execute
request that was triggered using Ajax

This needs clarification—does this mean to
say:

partial execute request (not triggered by
Ajax) or a partial execute request (that was triggered using Ajax)

===== "Execute portions" of the JSF request processing lifecycle in the JSF 2.0 Spec

Section 13.4.2 reads:

Although the diagram in Section 13.4 Partial
View Traversal˝ depicts the execute˝ portion as encompassing everything
except the Render Response Phase˝, it really is the Apply Request Values
Phase˝, Update Model Values Phase˝ and Process Validations Phase˝.

Why does the diagram include the
INVOKE_APPLICATION phase if it's not "really" considered to be part of
the execute portions?

==== Chapter 14

===== <<JavaScriptAPI.adoc#a6856,Initiating an Ajax Request>> Typo in table 14.2.2 of the JSF 2.0 Spec

Table 14.2.2 reads:

"execute" phase

But in order to be consistent with the rest
of the spec, it should read:

"execute" portion

Also, the same goes for "render" in that the
word "portion" should be used instead of "phase".

===== <<JavaScriptAPI.adoc#a6933,Request/Response Event Handling>> Table 14.4.1

Change responseTxt to responseText.

Table 14.3: Reorder rows

==== Appendix A Metadata

Update schema to remove partial-traversal, as
well as fixing 768.

==== VDLDoc changes

===== Typo in f:selectItems VDLDocs

Change "mest" to "must"

===== Need clarification on execute attribute of f:ajax

The VDLDocs for f:ajax say "Identifiers of
components" but, for some reason, it wasn't obvious to me that this term
referred to the "id" attributes of components. The recommendation isthat
this be clarified to say "list of <b>id</b> attribute values" instead.
Also, the value of an id attribute like "mycomponent" or something
should be added to an example that includes a keyword... something like
this: "@this componentone componenttwo"

===== Spelling error in VDLDocs for f:ajax

This one from Lincoln:

See the "onerror" attribute

There is an extra 'e' -> "oneerror"

===== Need clarification on required attribute in VDLDocs for tags that got a new "for" attribute in JSF 2.0

The VDLDocs correctly have green for the new
"for" attribute, but the "required" column says false, when that's not
always the case.

For example, with f:actionListener the
VDLDocs say that that it is not required. However, when the tag is used
as a child of a Composite Component, then the for attribute is indeed
required. This would be true of all tags like that, such as
f:convertDateTime, f:convertNumber, etc.

===== Uppercase typo in VDLDocs for f:event

Change uppercase "P" to lowercase for:
PostAddToView for the f:event VDLDocs

===== Need to change "JSP" to "Facelets" in "Body Content" of VDLDocs

Search for "JSP" on the f:event VDLDocs.
My suspicion is that this is a problem across the board.

===== Need clarification in VDLDocs for f:metadata

In the VDLDocs for f:metadata, recommend
changing:

"This tag must reside within the top level
XHTML file for the given viewId, not in a template"

to this:

"This tag must reside within the top level
Facelet view, or in a template-client, but not in a template"

Also, it needs to be clarified that the
page01.xhtml example is a template-client. So recommend changing this:

"viewId XHTML page, page01.xhtml"

to this:

"template-client XHTML page, page01.xhtml"

===== Missing description in VDLDocs for name attribute of f:viewParam

The VDLDocs for f:viewParam are missing
documentation of the "name" attribute, which is pretty important since
it is required.

===== VLDDocs on "for" attribute of f:viewParam claim it can be used in a CC

The VDLDocs for f:viewParam claim that the
"for" attribute is supported. I just checked Mojarra's jsf-api and
UIViewParameter.java does not support the "for" attribute, since it does
not have a getter/setter for "for" like HtmlOutputLabel does. There are
restrictions on f:viewParam such that it may only be used inside of
f:metadata, and f:metadata may only be used inside of f:view. So that
disqualifies the f:viewParam tag from being able to be used inside of a
Composite Component. Therefore I recommend that the documentation of the
"for" attribute be totally removed.

===== Miscellaneous VDLDoc items

* VDLDocs for "execute" attribute of f:ajax say
(must evaluate to java.lang.Object) but then say "Evaluates to
Collection"

* VDLDocs f:selectItem lists the new JSF 2.0
"noSelectionOption" but is not colored green to indicate "new in JSF
2.0" and the link for f:selectItem in the navigation frame needs to be
orange

* VDLDocs for f:validateBean should have all of
its attributes in green to indicate "new in JSF 2.0" since it is a new
tag.

* VDLDocs for f:validateRegex has a typo in the
description which reads "RegexpValidator" rather than "RegexValidator"

* In spec, the "Changes between 1.2 and EDR2"
section refers the reader to section 3.5.2 for the addition of
"javax.faces.RegularExpressionValidator" but actually it should be
section 3.5.5

* VDLDocs for h:button say that the outcome
attribute is not required, but really it should be required otherwise
there is no purpose of f:button—you would end up navigating back to
the current view. The whole point of f:button is to perform navigation
to a different view that potentially contains view parameters. Why have
a bookmarkable URL back to itself?

* VDLDocs for h:button don't mention a disabled
attribute, but the h:link one does have the disabled attribute. My guess
would be that both should have this attribute?

* VDLDocs for h:outputScript and
h:outputStylesheet should indicate that even though the UIOutput class
implements the ValueHolder interface, the coverter and value attributes
are basically ignored by the renderers, since the value attribute has no
meaning. This is basically a design flaw—a new class named
UIOutputResource should have been created instead of UIOutput being
reused.

* VDLDocs for h:outputScript and
h:outputStylesheet should indicate that the "name" attribute is
required, since section 2.6.1.3 implies that this is the case with the
following resource pattern:
[localePrefix/][libraryName/][libraryVersion/]resourceName[/resourceVersion]

* VDLDocs for h:outputScript needs to have all
the possible values for the target attribute documented. I think the
only valid values are "head", "body", and "form"

* VDLDocs for h:graphicImage has a dead
hyperlink to "Common Algorithm for Obtaining A Resource to Render

* VDLDocs for h:selectManyCheckbox indicate
orange for the collectionType and hideNoSelectionOption attributes but
they should be green to indicate "new in JSF 2.0"

* VDLDocs for h:selectManyCheckbox says that
the return type must evaluate to a String, but that's not entirely true.
It can also evaluate to a concrete class that implements
java.util.Collection

* VDLDocs for ui:param have two "name"
attributes specified. The second one should be the "value" attribute

===== Should TLDDocs now be VDLDocs?

The Spec introduces this term VDLDocs (which
as I said in the other email, was formerly PDLDocs), but it also refers
the reader to the TLDDocs. Should we just settle on VDLDocs as the
standard term throughout the Spec?

===== Typo in VDLDocs for f:event.

The VDLDocs for f:event specify a "name"
attribute, but the Description column of the page talks about a "type"
column (not "name"), which would be consistent with Section 3.4.3.4 of
the Spec which talks about a "type" column.

Jim Driscoll verified that there is a doc bug
in the VDLDocs for f:event and that the "name" attribute is actually
"type"

==== Accepted Changes from JCP Change Log for JSF 2.0 Rev a

The referenced spec public issue number can
be found in the issue tracker at +
{issue_tracker_url}





[width="100%",cols="7%,10%,56%,15%,12%",]
|===
|ID |Category
|Description
|Fixed in Source Code Repository of
Specification |Issue

|C002 |Errata
|Section 5.6.2.2 is out of sync with the
current resolver implementation. |yes
|
_{issue_tracker_url}848[Issue ID:848]_

|C004 |Errata
|RenderKitDoc for _OutcomeTarget_ Renderers
are incorrect with respect to intended design. Refer to
_link:appendixB-changelog.html#UNKNOWN[]ChangeC006_ in the
footnotes section below. |yes
|
_{issue_tracker_url}823[Issue ID:823]_

|C007 |Errata
|Section 11.4.7 "Ordering". After the
sentence "The <others /> element must be handled as follows" add a
bullet point: "The <others /> element represents a set of application
configuration resources. This set is described as the set of all
application configuration resources discovered in the application minus
the one currently being processed, minus the application configuration
resources mentioned by name in the <ordering /> section. If this set is
the empty set, at the time the application configuration resources are
being processed, the <others > element must be ignored."
|yes |
_{issue_tracker_url}824[Issue ID:824]_

|C008 |Errata
|taglib docs for cc:interface are
missing documentation for _componentType_ attribute.
|yes |
_{issue_tracker_url}849[Issue ID:849]_

|C011 |Errata
|Section 3.6.2.1 "Composite Component
Metadata". Add _BehaviorHolderAttachedObjectTarget_ after
iii. _ActionSource2AttachedObjectTarget_ |yes
|
_{issue_tracker_url}825[Issue ID:825]_

|C012 |Errata
|Javadocs for
_ResourceHandler.createResource(String resourceId)_ need to me ammended
to state that if there is an error in argument resourceId, null must be
returned by this method. |yes
|
_{issue_tracker_url}851[Issue ID:851]_

|C013 |Errata
|PDL DOCS: f:event listener attribute
clarification:Change description to: "A method expression that JSF
invokes when an event occurs. That event is specified with the name
attribute." |yes |
_{issue_tracker_url}586[Issue ID:586]_

|C015 |Errata
| _UIViewRoot.setBeforePhaseListeners()_
removed the statement that all phases including _RestoreView_ will have
their _beforePhaseListeners_ called. Reverted to the way it was in 1.2
|yes |
_{issue_tracker_url}826[Issue ID:826]_

|C016 |Errata
|Section 2.6.2.1 Relocatable Resources: code
snippet: <f:view..../> should be <f:view...>
|yes |
_{issue_tracker_url}565[Issue ID:565]_

|C017 |Errata
| _UISelectItem_ doesn't mention
__itemEscaped__. |yes
|
_{issue_tracker_url}430[Issue ID:430]_

|C018 |Errata
|
_ViewDeclarationLanguage.retargetAttachedObjects()_ misses talking about
Behaviors |yes |
_{issue_tracker_url}827[Issue ID:827]_

|C021 |Errata
|ui:insert missing existing "name" attribute,
implemented, tested, but not documented |yes
|
_{issue_tracker_url}667[Issue ID:667]_

|C022 |Errata
| _f:valueChangeListener_ missing "for"
attribute. Implemented, tested, but not documented
|yes |
_{issue_tracker_url}828[Issue ID:828]_

|C023 |Change
|in facelets VDLdoc, mark f:verbatim and
f:subview as deprecated |no
|
_{issue_tracker_url}852[Issue ID:852]_

|C024 |Errata
|Add an assertion to section 10.3.1 stating
that EL expressions that appear in the facelet XHTML page must appear in
the rendered view as if they were the right hand side of the value
attribute of an _<h:outputText>_ at the same point in the page as the EL
expression |yes |
_{issue_tracker_url}829[Issue ID:829]_

|C027 |Errata
|web-facelettaglibrary_2_0.xsd type incorrect
for composite-library-name. Should be ***javae:string***
|no |
_{issue_tracker_url}854[Issue ID:854]_

|C028 |Errata
| _ui:remove_ VDLDoc has attribute with no
name |no |
_{issue_tracker_url}842[Issue ID:842]_

|C029 |Errata
| _ui:param_ has attribute duplicated. One of
them should be "value" |yes
|
_{issue_tracker_url}855[Issue ID:855]_

|C030 |Errata
|RenderKit Docs _javax.faces.CompositeFacet_
change " The implementation of __encodeBegin()__, must obtain " to be "
The implementation of __encodeChildren()__, must obtain "
|no |
_{issue_tracker_url}843[Issue ID:843]_

|C031 |Errata
|VDL docs state that _cc:attribute_
has a target attribute with __required="true"__. This attribute is not
really required on __cc:attribute__.
|yes |
_{issue_tracker_url}644[Issue ID:644]_

|C032 |Errata
|Mention in spec that Objects put in view
scope may need to be Serializable |yes
|
_{issue_tracker_url}830[Issue ID:830]_

|C033 |Errata
|Modify the javadoc for _ResourceHandler_ to
state that for resources residing at
__META-INF/resources/<resourceidentifier>__. The implementation is not
required to support the optional _libraryVersion_ and _resourceVersion_
segments |yes |
_{issue_tracker_url}844[Issue ID:844]_

|C034 |Change
|Modify table 5-10 to state that implicit
object cc returns the current composite component, relative to the
composite component markup page in which the expression appears
|yes |
_{issue_tracker_url}831[Issue ID:831]_

|C035 |Errata
|3.6.2.1 Modify composite component metadata
specification to state that, within the _cc:interface_ element, the
following attributes are not available unless _ProjectStage_ is
__Development__: displayName, expert, hidden, preferred, shortDescription
|yes |
_{issue_tracker_url}832[Issue ID:832]_

|C037 |Errata
| _UIComponent.restoreState()_ javadocs must
be changed to ***say*** NPE is thrown if context is null, but no action
is taken if state argument is null |yes
|
_{issue_tracker_url}845[Issue ID:845]_

|C040 |Errata
|VDLDocs for __f:metadata__. Don't mention
__f:view__. State, "This tag must reside within the top level facelet
page whose filename corresponds ot the _viewid_ being loaded."
|yes |
_{issue_tracker_url}856[Issue ID:856]_

|C043 |Errata
|Document _SEPARATOR_CHAR_ in section 11.1.3
where all the other context-params are documented
|yes |
_{issue_tracker_url}833[Issue ID:833]_

|C044 |Errata
|Section 11.4.6 doesn't include
__ViewDeclarationLanguage__, __VisitContextFactory__,
__ExceptionHandlerFactory__, __PartialViewContext__,
_TagHandlerDelegateFactory_ as decoratable
|yes |
_{issue_tracker_url}834[Issue ID:834]_

|C046 |Errata
|Section 10.4.1.1 specifies the use of
_AjaxBehaviors pushBehavior_ but _AjaxBehaviors_ is an implementation
detail (the class exists under com package)
|yes |
_{issue_tracker_url}836[Issue ID:836]_

|C047 |Errata
|Add "defaults" for "execute", "render"
_AjaxBehavior_ in VDLDocs. |yes
|
_{issue_tracker_url}568[Issue ID:568]_

|C048 |Errata
|JSP should not have __f:viewParam__. Facelets
_f:viewParam_ must have _name_ attribute.
|yes |
_{issue_tracker_url}656[Issue ID:656]_

|C049 |Errata
|Spec section 3.2.5 is empty. Fix that
|yes |
_{issue_tracker_url}835[Issue ID:835]_

|C050 |Errata
|Spec for _UIComponent.setParent()_
incomplete |yes |
_{issue_tracker_url}837[Issue ID:837]_

|C054 |Errata
| _f:event name_ attribute should be type.
|yes |
_{issue_tracker_url}639[Issue ID:639]_

|C058 |Errata
|Section 14.4.1: Table 14-4: responseTxt
should be responseText. Table 14-4: Add _status_ property; Table 14-4:
There is no "name" property. Table 14-3: reorder "status" values to be
in chronological order. Section 14.4.1.1: Fix use case.
|yes |
_{issue_tracker_url}642[Issue ID:642]_

|C060 |Change
|Replace the last sentence in the javadoc for
_FacesServlet.service()_ to say "The implementation must make it so
_FacesContext.release()_ is called within a finally block as late as
possible in the processing for the JSF related portion of this request".
|yes |
_{issue_tracker_url}846[Issue ID:846]_

|C061 |Change
|Non-normatively document that JavaBeans
PropertyEditors will be used for EL Coercion. Mention this in the
context of JSF converters |yes
|
_{issue_tracker_url}838[Issue ID:838]_

|C062 |Change
|In 3.1.5, explicitly mention not to use view
scope |yes |
_{issue_tracker_url}839[Issue ID:839]_

|C063 |Change
|7.4.1 Clarify that, in the case of
navigation actions, an empty string should be treated the same way as
null: stay on the same page. |yes
|
_{issue_tracker_url}747[Issue ID:747]_

|C064 |Change
|Correct _StateHolder.setTransient_ JavaDoc
(specified backwards) |yes
|
_{issue_tracker_url}840[Issue ID:840]_

|C065 |Change
|Correct typos in _Composite.tld_ (for
pdldocs). Specifically, quotes around __actionListener__,
_method-signature_ (spelling). Also clarify the default value "false"
for "required" attribute. |yes
|
_{issue_tracker_url}841[Issue ID:841]_

|C066 |Change
|Specify that the Component Resource
container facet must be marked transient. Specifically, the JavaDocs for
_UIViewRoot.getComponentResources_ should include: "Set the transient
property of the facet to true." |yes
|
_{issue_tracker_url}800[Issue ID:800]_

|C068 |Change
|Modify the facelet taglib xsd so that older
versions of taglibs are acceptable. |yes
|
_{issue_tracker_url}744[Issue ID:744]_

|C069 |Change
|Make sure VDLDocs for _f:event_ list event
all possible event types |yes
|
_{issue_tracker_url}712[Issue ID:712]_

|C072 |Errata
|Neither applyNextHandler of
DelegatingMetaTagHandler or nextHandler of TagHandler are documented.
|yes |
_{issue_tracker_url}780[Issue ID:780]_

|C073 |Errata
|Specify f:ajax execute/render id behavior in
VDLDocs (as outlined in Section 10.4.1.1 of the spec).
|yes |
_{issue_tracker_url}567[Issue ID:567]_

|C074 |Errata
|<view-param> has no business being a child
of <redirect> and should be renamed to <redirect-param>.
|yes |
_{issue_tracker_url}698[Issue ID:698]_

|C075 |Errata
|includeViewParams implicit navigation flag
should be faces-include-view-params. |yes
|
_{issue_tracker_url}699[Issue ID:699]_

|C077 |Errata
|Event broadcasting should apply to Behaviors
(not just ClientBehaviors). |yes
|
_{issue_tracker_url}798[Issue ID:798]_

|C078 |Errata
|PostAddToViewEvent delivery specification
needs clarification. Clarify UIComponent.getParent and getChildren for
consistency. |yes
|
_{issue_tracker_url}805[Issue ID:805]_

|C079 |Errata
|RenderKit Docs - TableRenderer:Clarification
- the docs say to render the footer the same as the header which causes
the problem. |yes
|
_{issue_tracker_url}255[Issue ID:255]_

|C080 |Errata
|RenderKit Docs - ButtonRenderer Encode
behavior w/r/t onclick attribute - should not be passthrough attribute.
|yes |
_{issue_tracker_url}257[Issue ID:257]_

|C081 |Errata
|h:message "for" attribute is
mis-specified:"for" attribute should be relative id (not clientid).
|yes |
_{issue_tracker_url}266[Issue ID:266]_

|C082 |Errata
|clarify whether expression of
binding-attribute of f:xxxxListener should be evaluated on postback.
|yes |
_{issue_tracker_url}320[Issue ID:320]_

|C083 |Errata
|Option rendering, specifically when dealing
with SelectItemGroups, is too generic. |yes
|
_{issue_tracker_url}420[Issue ID:420]_

|C084 |Errata
|submittedValue get/set methods
underspecified |yes
|
_{issue_tracker_url}434[Issue ID:434]_

|C085 |Errata
|Current wording in renderkit docs leads to
double encoding of query parameters |yes
|
_{issue_tracker_url}436[Issue ID:436]_

|C086 |Errata
|SelectManyCheckBox Clarification
|yes |
_{issue_tracker_url}466[Issue ID:466]_

|C087 |Errata
|PDL document for JSTL(Facelets) has the
incorrect URI for the NameSpace. |yes
|
_{issue_tracker_url}509[Issue ID:509]_

|C088 |Errata
|API docs missing for ExceptionEventContext.
|yes |
_{issue_tracker_url}515[Issue ID:515]_

|C089 |Errata
|cc:attribute component documentation
for the attribute type should be for attribute method-signature.
|yes |
_{issue_tracker_url}524[Issue ID:524]_

|C090 |Errata
|The UML Diagram for javax.faces.event is out
of date. |yes |
_{issue_tracker_url}525[Issue ID:525]_

|C091 |Errata
|Minor typo in the Interface BehaviorHolder
API. |yes |
_{issue_tracker_url}534[Issue ID:534]_

|C092 |Errata
|Two references to the itemLabelEscaped
attribute. |yes |
_{issue_tracker_url}536[Issue ID:536]_

|C093 |Errata
|Missing class description for
javax.faces.event.PostValidateEvent and
javax.faces.event.PreValidateEvent. |yes
|
_{issue_tracker_url}537[Issue ID:537]_

|C094 |Errata
|Section 3.7.5 typo - ClientBehavorHolder
should be ClientBehaviorHolder. |yes
|
_{issue_tracker_url}540[Issue ID:540]_

|C095 |Errata
|Section 4.1.3 typo - NamingContaier should
be NamingContainer. |yes
|
_{issue_tracker_url}541[Issue ID:541]_

|C096 |Errata
|API Docs: Application.publishEvent: Docs say
to throw NPE if any of the arguments is null. However, sourceBaseType
arg can be null. |yes
|
_{issue_tracker_url}553[Issue ID:553]_

|C097 |Errata
|Facelets TLD Docs: Missing "for" attribute
for "message" and "messages" tags. |yes
|
_{issue_tracker_url}558[Issue ID:558]_

|C099 |Errata
|ResourceHandler docs: Clarify that relative
paths are disallowed in library names. |yes
|
_{issue_tracker_url}577[Issue ID:577]_

|C100 |Errata
|Renderkit Docs: h:link - Formatting - add
paragraphs |yes |
_{issue_tracker_url}588[Issue ID:588]_

|C101 |Errata
|Spec Section 2.5.9: Fix Grammar: "The first
client behavior to provided by the JSF specification is the
AjaxBehavior." should be: "The first client behavior provided by the JSF
specification is the AjaxBehavior." |yes
|
_{issue_tracker_url}590[Issue ID:590]_

|C102 |Errata
|Spec Section 9.4 doesn't list all the
validation tags and it lists the validateDoubleRange tag twice.
|no |
_{issue_tracker_url}591[Issue ID:591]_

|C103 |Errata
|VDLDocs and Spec section 3.6.2.1 have
component:actionSource target attribute with commas as delimiters -
should be "space" as delimiter. |yes
|
_{issue_tracker_url}592[Issue ID:592]_

|C104 |Errata
|Spec Section 7.4.1: getNavigationCase should
return NavigationCase and not void. |yes
|
_{issue_tracker_url}605[Issue ID:605]_

|C105 |Errata
|Spec Section 10.4.1.4 says: f:validateBean
should extend validateHandler. Should be ValidatorHandler.
|yes |
_{issue_tracker_url}615[Issue ID:615]_

|C106 |Errata
|Typo: Pages in the TLD docs says "JSF 2.0
Page Decraration Language". Should be "Declaration".
|yes |
_{issue_tracker_url}617[Issue ID:617]_

|C107 |Errata
|Typos: Table 14-1, 14-2, page 14-3.
|yes |
_{issue_tracker_url}629[Issue ID:629]_

|C108 |Errata
|UIData.invokeOnComponent docs need to be
updated to include handling of column level facets.
|yes |
_{issue_tracker_url}632[Issue ID:632]_

|C109 |Errata
|Spec Section 3.5.6.1 needs to be corrected
to state that default validators are added during tag execution time.
|yes |
_{issue_tracker_url}635[Issue ID:635]_

|C110 |Errata
|validateBean and validateRequired tags need
to be removed from the Jakarta Server Pages PDL documentation
|yes |
_{issue_tracker_url}645[Issue ID:645]_

|C111 |Errata
|faces.ajax.response update element
clarification needed in JavaScript docs. |yes
|
_{issue_tracker_url}646[Issue ID:646]_

|C112 |Errata
|Spec Section 10.4.1.1: Clarify what happens
when nesting and wrapping f:ajax tags collide.
|yes |
_{issue_tracker_url}652[Issue ID:652]_

|C113 |Errata
|Typo: Spec Section 8.3.1: "renderkit-id"
should be "render-kit-id" and "renderkit" should be "render-kit".
|yes |
_{issue_tracker_url}660[Issue ID:660]_

|C114 |Errata
|Add "rendered" attribute to VDL docs for
ui:component and ui:fragment. |yes
|
_{issue_tracker_url}661[Issue ID:661]_

|C115 |Errata
|JavaDocs for UIComponent.processValidators
is incomplete. It should mention __popComponentFromEL__.
|yes |
_{issue_tracker_url}664[Issue ID:664]_

|C116 |Errata
|Dead link in VDL docs.
|yes |
_{issue_tracker_url}666[Issue ID:666]_

|C117 |Errata
|Spec Section 2.5.2.4: Standard messages for
LengthValidator are confusing. |yes
|
_{issue_tracker_url}668[Issue ID:668]_

|C118 |Errata
|Spec/pdldocs don't say what the default is
for "target" in h:outputScript. |yes
|
_{issue_tracker_url}673[Issue ID:673]_

|C119 |Errata
|partial-view-context-factory is only
mentioned in the schema part of the spec. Houls be added to Spec Section
13.4.2. |yes |
_{issue_tracker_url}705[Issue ID:705]_

|C120 |Errata
|Specification edits needed
|no |
_{issue_tracker_url}714[Issue ID:714]_

|C121 |Errata
|Typo - Spec Section 7.5.2: "ViewHanlder"
should be "ViewHandler"; "renderView" and "restoreView" methods should
call "ViewDeclarationLanguage.renderView" and
"ViewDeclarationLanguage.restoreView". |yes
|
_{issue_tracker_url}729[Issue ID:729]_

|C122 |Errata
|Spec Section 2.6.1.3: Specify that a
libraryName or resourceName contains only XML NameChar, but not a colon;
a libraryName or resourceName does not match the regex
+++"[0-9]+(_[0-9]+)* or [A-Za-z]{2}(_[A-Za-z]{2}(_[A- Za-z]+)*)?"+++
|yes |
_{issue_tracker_url}740[Issue ID:740]_

|C123 |Errata
|Typos in PDLDocs for ui:repeat
|yes |
_{issue_tracker_url}743[Issue ID:743]_

|C124 |Errata
|Remove "partial-traversal" application
element from the spec as it does not exist in the schema.
|yes |
_{issue_tracker_url}767[Issue ID:767]_

|C125 |Errata
|Add mssing ID attributes to schema for:
faces-config-orderingType,faces-config-ordering-orderingType,faces-config-absoluteOrderingType,faces-config-default-valueType,faces-config-from-view-idType,faces-config-client-behavior-rendererType,faces-config-behaviorType,faces-config-value-classType,faces-config-rendererType
|yes |
_{issue_tracker_url}768[Issue ID:768]_

|C126 |Errata
|UIInput JavaDocs: Specify the handling of
conversion failures. |yes
|
_{issue_tracker_url}775[Issue ID:775]_

|C127 |Errata
|EditableValueHodler JavaDocs: Missing
"@Since 2.0" for "resetValue" method. |yes
|
_{issue_tracker_url}779[Issue ID:779]_

|C128 |Errata
|VDL documentation for f:selectItem
references the "escape" attribute. It should be "itemEscaped".
|yes |
_{issue_tracker_url}788[Issue ID:788]_

|C129 |Errata
|Specify description for "f:param" "disabled"
attribute. |yes |
_{issue_tracker_url}794[Issue ID:794]_

|C130 |Errata
|Simplify PostRestoreStateEvent delivery
requirements. |yes
|
_{issue_tracker_url}806[Issue ID:806]_
|===














=== Changes in versions below 2.0 Final

See the "JavaServer™ Faces Specification Version 2.3" for these changes.
The change log items are removed from this document in Jakarta Faces 3.0.
