[appendix]
== Change Log

=== Changes between 2.1 and 2.2

This section gives the reader a survey of the
changes between this version of the specification and the previous
version, using the categories from the issue tracker at <
http://jsf-spec.java.net/issues/ >.

==== Big Ticket Features

* HTML5 Friendly Markup +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1090 +
Start with
<<FaceletsAndWebApplications.adoc#a5581,See HTML5 Friendly Markup>>

* Resource Library Contracts +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1142 +
Start with <<FaceletsAndWebApplications.adoc#a5526,
Resource Library Contracts Background>>.

* Faces Flows +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-730 +
Start with <<ApplicationIntegration.adoc#a3840,
FlowHandler>>.

* Stateless Views +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1055 +
Start with <<ApplicationIntegration.adoc#a4126,
Stateless Views>>.

==== Other Features, by Functional Area

===== Components/Renderers

.Larger Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-479-UIDataCollection +
UIData supports the Collection Interface rather than List.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1134 +
Add the "role" pass through attribute.

.Smaller Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1080-FindComponentWarning +
Warn about some important corner cases when
_UIComponent.findComponent()_ may not provide the expected results.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1068-PartialResponseProcessing +
New section describing what happens with
respect to partial processing during render response. See
<<RequestProcessingLifecycle.adoc#a480,Render Response Partial Processing>>.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1067-cc:insertChildren +
Spec clarifications. See the VDLDoc for _cc:insertChildren_ ,
_cc:insertFacet_

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1061 +
Clarify that both
_Application.publishEvent()_ and the manual traversal based delivery are
required for publishing the _PostRestoreStateEvent_ .

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1030 +
Clarify docs for h:message h:messages

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1023 +
Modify JavaDoc to relax requirements for PostAddToViewEvent publishing

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1019 +
Modify spec for ResponseWriter.writeURIAttribute() to explicitly require
adherence to the W3C URI spec

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-997 +
javax.faces.component.ComponentSystemEvent: Override
isAppropriateListener so that it first asks the listener, "are you a
ComponentSystemEventListener", then, if not, asks
super.isAppropriateListener()

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-984 +
Component Context Manager, see
_javax.faces.component.visit.ComponentModificationManager_ .

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-943 +
See _javax.faces.view.ViewDeclarationLanguageWrapper_

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-784 +
Deprecate the CURRENT_COMPONENT and CURRENT_COMPOSITE_COMPONENT
attributes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-599 +
Make it possible to programmatically create components in the same way
as they are created by Facelets. See
_javax.faces.application.Application.createComponent(FacesContext,
String taglibUri, String tagName, Map attrs)_

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-703 +
Make "value" optional for @FacesComponent.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-585 +
outputText and inputText do not render children by default

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-550 +
OutputStylesheet "media" attribute

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1125 +
_javax.faces.application.Application_ event subscription clarifications.

===== Lifecycle

.Larger Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-949-ClientWindow +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-947-ClientWindow +
Give JSF the ability to correctly handle browsing context (tab, browser
window, pop-up, etc). See _javax.faces.lifecycle.ClientWindow_ .

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-758-f:viewAction
and +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1042
+
A jsf-api/src/main/java/javax/faces/component/UIViewAction.java
+
--
[none]
* The heart of this changebundle, this class
came over from the JBoss Seam Faces Module, but I've rewritten most of
the javadoc.
--
+
M jsf-api/src/main/java/javax/faces/event/PhaseId.java
+
--
[none]
* new methods +
* public String getName() +
* public static PhaseId phaseIdValueOf(String phase)
--
+
Change <<ApplicationIntegration.adoc#a3571,
Default NavigationHandler Algorithm>> to account for UIViewAction

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1062 and +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-802 +
File Upload

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-766 +
Events from the flash

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1050 +
Add support for delay value in options for Ajax requests

.Smaller Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1129 +
In validate(), clarify that setSubmittedValue() null must be called if
validation succeeds.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1071 +
Add FlashFactory. See
<<UsingJSFInWebApplications.adoc#a6336,Delegating Implementation Support>>.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1065 +
When calculating the locale for the
resource library prefix, if there is a UIViewRoot, use its locale first,
otherwise, just use the Applications’s ViewHandler’s calculateLocale()
method. See <<RequestProcessingLifecycle.adoc#a836,Libraries of Localized and
Versioned Resources>>

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1039 +
In ApplicationWrapper, mark things as deprecated

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1028 +
Deprecate StateManager, point to StateManagementStrategy. In
StateManagementStrategy, require the use of the visit API to perform the
saving.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-993 +
Wrapper for ActionListener

* Tweak circumstances for skipping intervening
lifecycle phases in the case of view metadata +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-762 
+
--
[none]
* Section 2.2.1. Now has this text.
+
Otherwise, call getViewMetadata() on the
ViewDeclarationLanguage instance. If the result is non-null, call
createMetadataView() on the ViewMetadata instance. Call
ViewMetadata.getViewParameters(). If the result is a non-empty
Collection, do not call facesContext.renderResponse(). If the result is
an empty collection, try to obtain the metadata facet of the UIViewRoot
by asking the UIViewRoot for the facet named
UIViewRoot.METADATA_FACET_NAME. This facet must exist. If the facet has
no children, call facesContext.renderResponse(). Otherwise, none of the
previous steps have yielded the discovery any of metadata, so call
facesContext.renderResponse().
--

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-566 +
UIOutput.getValue() value returns.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-220 +
In web-partialresponse_2_2.xsd, require that
the <partial-response> element has an “id” attribute whose value is the
return from _UIViewRoot.getContainerClientId()_.



===== Platform Integration

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-763 +
Change <<ExpressionLanguageAndManagedBeanFacility.adoc#a2536,
Managed Bean Annotations>> to account for new injectability requirements.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-976 +
In Javadoc for “Faces Managed Bean Annotation Specification For
Containers Conforming to Servlet 2.5 and Beyond”, indicate that
_javax.faces.bean_ will be deprecated in the next version.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1087 +
Introduce CDI based @ViewScoped annotation.

===== Facelets/VDL

.Larger Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1001 +
Allow cc and non-cc components in one taglib
+
A jsf-api/doc/web-facelettaglibrary_2_2.xsd
+
First change to the facelet taglib schema in
2.2: introduce the ability to declare a resource which will be the
composite component for a tag. Now, before you get all excited about
what conventions we can use to make this easier, let me stop you right
there. Here is a summary of the ease of use story regarding taglib
files.
+
--
[none]
* The 80/20 rule says we should make taglib
files optional most of the time. Here are the 80% cases.

* Employs the cc naming convention
\http://java.sun.com/jsf/composite/<libraryName>

* The user employs a java component has a
@FacesComponent on it that declares the necessary metadata. +
JAVASERVERFACES_SPEC_PUBLIC-594
--
+
Here are some of the cases where you must
have a taglib file, the 20% cases.
+
--
[none]
* If you want to employ a cc with a namespace
other than \http://java.sun.com/jsf/composite/<libraryName> you need to
have a taglib file that declares <composite-library-name>. Currently you
must not detlare any <tag> elements in such a taglib file. All the tags
in such a library must come from the same resource library.

* If the user is not employs a java component
but is not using @FacesComponent.
--
+
This patch introduces the following syntax.
+
--
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<facelet-taglib xmlns="http://java.sun.com/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
        http://java.sun.com/xml/ns/javaee/web-facelettaglibary_2_2.xsd"
    version="2.2">
  <namespace>test</namespace>
  <tag>
    <tag-name>layout</tag-name>
    <resource-id>myCC/whatever.xhtml</resource-id>
  </tag>
</facelet-taglib>
----
--
+
Where _<resource-id>_ is a valid resource
identifier as specified in section 2.6.1.3.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-548 +
Require additional check to handle the case
where, in one resource library, there are both localized and
non-localized resources. See <<RequestProcessingLifecycle.adoc#a836,Libraries
of Localized and Versioned Resources>>.

.Smaller Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1038 +
Declare an annotation corresponding to the
_javax.faces.FACELETS_RESOURCE_RESOLVER_ application configuration
parameter. See <<UsingJSFInWebApplications.adoc#a6598,Requirements for scanning
of classes for annotations>> and <<UsingJSFInWebApplications.adoc#a6088,
Application Configuration Parameters>>.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1082 +
Account for DOCTYPE discrepancy between
server side representation of Facelet VDL files, which are proper XHTML,
and processed files which are sent to the client, which now, by default,
are HTML5 HTML syntax files. See <<JSFMetadata.adoc#a7061,The
facelets-processing element>>.

* Fix incorrect VDLDoc
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-967
f:selectItems itemValue description incorrect.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-922 +
Remove maxlength from f:viewParam

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-998 +
Document that ui:fragment should not be bound to a bean with wider than
request scope, document that the type of the property must extend from
UIComponent.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-999 +
Changes to "template" attribute requiredness for ui:decorate and
ui:composition

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-901 +
Deprecate “targets” concept.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1088 +
add short-name to schema.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-746 +
Missing _method-signature_ element in taglib xsd.

===== Spec Clarifications

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1136 +
In _ExternalContext.dispatch()_ , clarify what is to be done if
_getRequestDispatcher()_ returns _null_ .

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1132 +
Replace literal strings with symbolic constants where possible.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1127 +
State Saving Serializability concerns.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1114 +
_javax.faces.view.facelets.Facelet.apply()_ spec version reference
error.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1100 +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1097 +
HTML5 id attribute sensitivity

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1064 +
In <<JSFMetadata.adoc#a7061,The
facelets-processing element>>, clarify that in XML and JSPX modes, only
the CDATA section start and end tags, not the entire CDATA section and
contents, should be consumed.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1063 +
_javax.faces.component.UIViewParameter.getSubmittedValue()_ return
value.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1058 +
ui:repeat tag size attribute

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1036 +
In <<UserInterfaceComponentModel.adoc#a911,
ValueExpression properties>>, clarify which attributes are expression
enabled,

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1035 +
Change section
<<Per-RequestStateInformation.adoc#a3300,FacesMessage>> to clarify the meaning of
having _FacesMessage_ instances on the _FacesContext._

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1026 +
f:ajax event attribute is String (not VE)

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1014 +
12.1.3
+
--
[none]
* The specification for the context-param that
declares the list of TagDecorator implementations to the runtime should
have always been javax.faces.FACELETS_DECORATORS. Prior to this
revision, the name of this context param was incorrectly specified as
javax.faces.DECORATORS. The reference implementation has always used the
correct name, however.
--

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1010 +
Check existing usages of the state saving method parameter to ensure
case insensitivity.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1004 +
M usingFacesInWebapps.fm
+
--
[none]
* 12.1.3 Set default for
javax.faces.FACELETS_BUFFER_SIZE to be 1024.
--

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-998 +
Additional clarification about binding attribute in VDLdocs

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-915 +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1015 +
Non-normative text about http methods and prefix mapping

* http://java.net/jira/browse/JAVASERVERFACES-2740 +
In <<UserInterfaceComponentModel.adoc#a923,Component Bindings>>, clarify a corner
case regarding bean scope and component binding.

===== Resources

.Larger Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-809 +
This commit introduces a cleaner contract for allowing views to be
loaded from the Filesystem (including inside of JAR files). All VDL
resources must be loaded using ResourceHandler.createViewResource().

.Smaller Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-996 +
Enable configuring the web app resources
directory. See <<UsingJSFInWebApplications.adoc#a6088,Application Configuration
Parameters>>.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-719 +
Method to map a viewId to a resourcePath

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1130-SerializeServerState +
Modify <<ApplicationIntegration.adoc#a4135,State Saving Alternatives and
Implications>> to clarify there is no requirement to serialize server
state by default when state saving method is server. Introduce a context
parameter to this effect in <<UsingJSFInWebApplications.adoc#a6088,Application
Configuration Parameters>>

===== Expression Language

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1092
+
Remove text from
MethodExpressionValueChangeListener and MethodExpressionActionListener
regarding wrapping any exception thrown by the invoked method being
wrapped in an AbortProcessingException. Such a requirement is incorrect
and should not have been introduced.
+
In section <<Per-RequestStateInformation.adoc#a3253,
ExceptionHandler>>, add _AbortProcessingException_ , to the list of
exceptions that do not get to the _ExceptionHandler_ .

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1043 +
When publishing a ComponentSystemEvent, ensure the EL current component
is pushed correctly

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1164 +
If running in a container that supports EL 3.0, add the necessary
ELResolvers. See <<ExpressionLanguageAndManagedBeanFacility.adoc#a2966,See Stream, StaticField,
Map, List, Array, and Bean ELResolvers>>.

===== Configuration and Bootstrapping

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-533-ProgrammaticFacesConfig +
Modify <<UsingJSFInWebApplications.adoc#a6201,
Application Startup Behavior>> to account for requirement to call new API
when starting up.

===== Miscellaneous

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1169
+
New XML Namespace for XSD files introduced in
JSF 2.2, and also for facelet tag libraries.
+
The following XSD files are new for JSF 2.2,
and each will be in the XML namespace
_http://xmlns.jcp.org/xml/ns/javaee_ .
+
--
[none]
* _web-facelettaglibrary_2_2.xsd_

* _web-facesconfig_2_2.xsd_

* _web-partialresponse_2_2.xsd_
--
+
Facelet Tag Libraries will now respond to the
following URIs
+
--
[width="100%",cols="24%,38%,38%",options="header",]
|===
|Library |Old URI
|New URI
|Composite Components
|http://java.sun.com/jsf/composite a|
http://xmlns.jcp.org/jsf/composite



|Faces Core
|http://java.sun.com/jsf/core a|
http://xmlns.jcp.org/jsf/core



|HTML_BASIC
|http://java.sun.com/jsf/html a|
http://xmlns.jcp.org/jsf/html



|JSTL Core a|
http://java.sun.com/jsp/jstl/core



a|
http://xmlns.jcp.org/jsp/jstl/core



|JSTL Functions
|http://java.sun.com/jsp/jstl/functions a|
http://xmlns.jcp.org/jsp/jstl/functions



|Facelets Templating
|http://java.sun.com/jsf/facelets a|
http://xmlns.jcp.org/jsf/facelets



|Pass Through Attributes
|http://java.sun.com/jsf/passthrough a|
http://xmlns.jcp.org/jsf/passthrough



|Pass Through Elements
|http://java.sun.com/jsf a|
http://xmlns.jcp.org/jsf



|===
--
+
Developers are requested to use the values
from the New URI column, though both columns will work.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-997
+
M jsf-api/src/main/java/javax/faces/event/ComponentSystemEvent.java
+
--
[none]
* Override isAppropriateListener so that it
first asks the listener, "are you a ComponentSystemEventListener", then,
if not, asks super.isAppropriateListener()
--
+
M jsf-api/src/main/java/javax/faces/event/SystemEvent.java
+
--
[none]
* in isAppropriateListener(), document the
default implementation.
--
+
M jsf-api/src/main/java/javax/faces/component/UIComponent.java
+
--
[none]
* Make inner class
ComponentSystemEventListenerAdapter implement
ComponentSystemEventListener.
--

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-917
+
javax.faces.application.ResourceWrapper:
+
--
[none]
* getContentType()

* getLibraryName()

* getResourceName()

* setContentType(String)

* setLibraryName(String)

* setResourceName(String)
--
+
javax.faces.context.ExternalContextWrapper:
+
--
[none]
* getSessionMaxInactiveInterval()

* isSecure()

* setSessionMaxInactiveInterval()
--
+
javax.faces.context.PartialViewContextWrapper
+
--
[none]
* setPartialRequest(boolean)
--

* 12.1.3 add this text to the
javax.faces.STATE_SAVING_METHOD spec. +
When examining the value, the
runtime must ignore the case.

* Add
ExternalContext.getApplicationContextPath() +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1012

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-787 +
restore ViewScope before templates are processed with buildView()

* 7.6.2.6 typo in spec for renderView(). Should be +
Return immediately if calling isRendered() on
the argument UIViewRoot returns false.

* Per Matt Benson, remove duplicate
descriptions of the cc and component implicit object from the getValue()
specification for the composite component ELResolver in section 5.6.2.1.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-869
+
Specify Cross Site Request Forgery
protection.
+
Add text in <<RequestProcessingLifecycle.adoc#a404,
Restore View>> to describe how non-postback requests are inspected for
protection, if necessary.
+
Remove text for writeState() in
<<RenderingModel.adoc#a4288,ResponseStateManager>>, point to the
JavaDocs.
+
Add View Protection methods to
<<ApplicationIntegration.adoc#a3874,Overview>> for ViewHandler.
+
Introduce subsections to
<<ApplicationIntegration.adoc#a3910,Default ViewHandler Implementation>> that
group the methods by their purpose. Add a new section
<<ApplicationIntegration.adoc#a3997,ViewHandler Methods that relate to View
Protection>>, which points to the javadocs. In
<<ApplicationIntegration.adoc#a3955,ViewHandler Methods Relating to
Navigation>>, in the spec for _getActionUrl()_ , specify how view
protection is affected.

* Remove tables in section
<<UsingJSFInWebApplications.adoc#a6598,Requirements for scanning of classes for
annotations>> +
The Javadoc tool lists annotations in a
separate section, making the tables that list JSF related annotations
redundant.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1082-DoctypeElement +
Add new section
<<FaceletsAndWebApplications.adoc#a5635,DOCTYPE and XML Declaration>>.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1141-SlashInResourceNames +
In <<RequestProcessingLifecycle.adoc#a758,Resource
Identifiers>>, declare that resourceName and resourceVersion, in addition
to the already listed other segments, are subject to the same
constraints.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1129-ResetValues +
In <<RequestProcessingLifecycle.adoc#a480,Render
Response Partial Processing>>, require calling _UIViewRoot.resetValues()_
if necessary.

==== Backward Compatibility with Previous Versions

Faces 2.2 is backwards compatible with Faces
2.1 and 2.0. This means that a web-application that was developed to run
with Faces 2.1 or 2.0 won’t require any modification when run with Faces
2.2 except in the cases described in the following section.

==== Breakages in Backward Compatibility

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1092 +
Due to an error in previous versions of the
specification, exceptions were silently being swallowed that now will
bubble up to the exception handler. Code that was relying on this
incorrect behavior may need to be modified to account for fixing this
problem.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-745
+
5.6.2.2 Table 5-11. Make the following
changes to the spec for Composite Component Attribute ELResoler
+
--
[none]
* Modify getType() according to new
specification language.

* Require the implementation of containsKey()
on the Map.
+
====
[none]
* containsKey(): If the attributes map contains
the key, return true. Otherwise, if a default value has been declared
for the attribute, return true. Otherwise, return false.
====
+
--
+
<<UserInterfaceComponentModel.adoc#a1671,
Composite Component Metadata>>
+
New text dealing with <cc:attribute>
+
--
[none]
* Any additional attributes on
_<composite:attribute/ >_ are exposed as attributes accessible from the
_getValue()_ and _attributeNames()_ methods on _PropertyDescriptor_ .
The return type from getValue() must be a _ValueExpression_ with the
exception of the _getValue(“type”)_ . The return type from
_getValue(“type”)_ must be _Class_ . If the value specified for the
_type_ attribute of _<cc:attribute/>_ cannot be converted to an actual
_Class_ , a _TagAttributeException_ must be thrown, including the _Tag_
and _TagAttribute_ instances in the constructor.
--

Yes, this is a backwards incompatible change,
but because the usecase is so specific, and the performance benefit so
substantial, it was judged to be worth the cost.




=== Changes between 2.1 and 2.2

This section gives the reader a survey of the
changes between this version of the specification and the previous
version, using the categories from the issue tracker at <
http://jsf-spec.java.net/issues/ >.

==== Big Ticket Features

* HTML5 Friendly Markup +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1090 +
Start with
<<FaceletsAndWebApplications.adoc#a5581,HTML5 Friendly Markup>>

* Resource Library Contracts +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1142 +
Start with <<FaceletsAndWebApplications.adoc#a5526,
Resource Library Contracts Background>>.

* Faces Flows +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-730 +
Start with <<ApplicationIntegration.adoc#a3840,
FlowHandler>>.

* Stateless Views +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1055 +
Start with <<ApplicationIntegration.adoc#a4126, +
Stateless Views>>.

==== Other Features, by Functional Area

===== Components/Renderers

.Larger Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-479-UIDataCollection +
UIData supports the Collection Interface rather than List.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1134 +
Add the "role" pass through attribute.

.Smaller Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1080-FindComponentWarning +
Warn about some important corner cases when
_UIComponent.findComponent()_ may not provide the expected results.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1068-PartialResponseProcessing +
New section describing what happens with
respect to partial processing during render response. See
<<RequestProcessingLifecycle.adoc#a480,Render Response Partial Processing>>.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1067-cc:insertChildren +
Spec clarifications. See the VDLDoc for _cc:insertChildren_ ,
_cc:insertFacet_

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1061 +
Clarify that both
_Application.publishEvent()_ and the manual traversal based delivery are
required for publishing the _PostRestoreStateEvent_ .

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1030 +
Clarify docs for h:message h:messages

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1023 +
Modify JavaDoc to relax requirements for PostAddToViewEvent publishing

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1019 +
Modify spec for ResponseWriter.writeURIAttribute() to explicitly require
adherence to the W3C URI spec

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-997 +
javax.faces.component.ComponentSystemEvent: Override
isAppropriateListener so that it first asks the listener, "are you a
ComponentSystemEventListener", then, if not, asks
super.isAppropriateListener()

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-984 +
Component Context Manager, see
_javax.faces.component.visit.ComponentModificationManager_ .

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-943 +
See _javax.faces.view.ViewDeclarationLanguageWrapper_

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-784 +
Deprecate the CURRENT_COMPONENT and CURRENT_COMPOSITE_COMPONENT
attributes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-599 +
Make it possible to programmatically create components in the same way
as they are created by Facelets. See
_javax.faces.application.Application.createComponent(FacesContext,
String taglibUri, String tagName, Map attrs)_

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-703 +
Make "value" optional for @FacesComponent.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-585 +
outputText and inputText do not render children by default

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-550 +
OutputStylesheet "media" attribute

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1125 +
_javax.faces.application.Application_ event subscription clarifications.

===== Lifecycle

.Larger Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-949-ClientWindow +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-947-ClientWindow +
Give JSF the ability to correctly handle browsing context (tab, browser
window, pop-up, etc). See _javax.faces.lifecycle.ClientWindow_ .

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-758-f:viewAction
and +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1042
+
A jsf-api/src/main/java/javax/faces/component/UIViewAction.java
+
--
[none]
* The heart of this changebundle, this class
came over from the JBoss Seam Faces Module, but I've rewritten most of
the javadoc.
--
+
M jsf-api/src/main/java/javax/faces/event/PhaseId.java
+
--
[none]
* new methods

* public String getName()

* public static PhaseId phaseIdValueOf(String
phase)
--
+
Change <<ApplicationIntegration.adoc#a3571,
Default NavigationHandler Algorithm>> to account for UIViewAction

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1062 and +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-802 +
File Upload

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-766 +
Events from the flash

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1050 +
Add support for delay value in options for Ajax requests

.Smaller Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1129 +
In validate(), clarify that setSubmittedValue() null must be called if
validation succeeds.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1071
Add FlashFactory. See
<<UsingJSFInWebApplications.adoc#a6336,Delegating Implementation Support>>.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1065 +
When calculating the locale for the
resource library prefix, if there is a UIViewRoot, use its locale first,
otherwise, just use the Applications’s ViewHandler’s calculateLocale()
method. See <<RequestProcessingLifecycle.adoc#a836,Libraries of Localized and
Versioned Resources>>

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1039 +
In ApplicationWrapper, mark things as deprecated

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1028 +
Deprecate StateManager, point to StateManagementStrategy. In
StateManagementStrategy, require the use of the visit API to perform the
saving.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-993 +
Wrapper for ActionListener

* Tweak circumstances for skipping intervening
lifecycle phases in the case of view metadata
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-762
+
Section 2.2.1. Now has this text.
+
--
[none]
* Otherwise, call getViewMetadata() on the
ViewDeclarationLanguage instance. If the result is non-null, call
createMetadataView() on the ViewMetadata instance. Call
ViewMetadata.getViewParameters(). If the result is a non-empty
Collection, do not call facesContext.renderResponse(). If the result is
an empty collection, try to obtain the metadata facet of the UIViewRoot
by asking the UIViewRoot for the facet named
UIViewRoot.METADATA_FACET_NAME. This facet must exist. If the facet has
no children, call facesContext.renderResponse(). Otherwise, none of the
previous steps have yielded the discovery any of metadata, so call
facesContext.renderResponse().
--

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-566 +
UIOutput.getValue() value returns.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-220 +
In web-partialresponse_2_2.xsd, require that
the <partial-response> element has an “id” attribute whose value is the
return from _UIViewRoot.getContainerClientId()_ .



===== Platform Integration

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-763 +
Change <<ExpressionLanguageAndManagedBeanFacility.adoc#a2536,
Managed Bean Annotations>> to account for new injectability requirements.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-976 +
In Javadoc for “Faces Managed Bean Annotation Specification For
Containers Conforming to Servlet 2.5 and Beyond”, indicate that
_javax.faces.bean_ will be deprecated in the next version.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1087 +
Introduce CDI based @ViewScoped annotation.

===== Facelets/VDL

.Larger Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1001 +
Allow cc and non-cc components in one taglib
+
A jsf-api/doc/web-facelettaglibrary_2_2.xsd
+
First change to the facelet taglib schema in
2.2: introduce the ability to declare a resource which will be the
composite component for a tag. Now, before you get all excited about
what conventions we can use to make this easier, let me stop you right
there. Here is a summary of the ease of use story regarding taglib
files.
+
--
[none]
* The 80/20 rule says we should make taglib
files optional most of the time. Here are the 80% cases.

* Employs the cc naming convention
\http://java.sun.com/jsf/composite/<libraryName>

* The user employs a java component has a
@FacesComponent on it that declares the necessary metadata.
JAVASERVERFACES_SPEC_PUBLIC-594
--
+
Here are some of the cases where you must
have a taglib file, the 20% cases.
+
--
[none]
* If you want to employ a cc with a namespace
other than \http://java.sun.com/jsf/composite/<libraryName> you need to
have a taglib file that declares <composite-library-name>. Currently you
must not detlare any <tag> elements in such a taglib file. All the tags
in such a library must come from the same resource library.

* If the user is not employs a java component
but is not using @FacesComponent.
--
+
This patch introduces the following syntax.
+
[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<facelet-taglib xmlns="http://java.sun.com/xml/ns/javaee"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
    http://java.sun.com/xml/ns/javaee/web-facelettaglibary_2_2.xsd"
    version="2.2">
  <namespace>test</namespace>
  <tag>
    <tag-name>layout</tag-name>
    <resource-id>myCC/whatever.xhtml</resource-id>
  </tag>
</facelet-taglib>
----
+
Where _<resource-id>_ is a valid resource
identifier as specified in section 2.6.1.3.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-548 +
Require additional check to handle the case
where, in one resource library, there are both localized and
non-localized resources. See <<RequestProcessingLifecycle.adoc#a836,See Libraries
of Localized and Versioned Resources>>.

.Smaller Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1038 +
Declare an annotation corresponding to the
_javax.faces.FACELETS_RESOURCE_RESOLVER_ application configuration
parameter. See <<UsingJSFInWebApplications.adoc#a6598,See Requirements for scanning
of classes for annotations>> and <<UsingJSFInWebApplications.adoc#a6088,See
Application Configuration Parameters>>.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1082 +
Account for DOCTYPE discrepancy between
server side representation of Facelet VDL files, which are proper XHTML,
and processed files which are sent to the client, which now, by default,
are HTML5 HTML syntax files. See <<JSFMetadata.adoc#a7061,See The
facelets-processing element>>.

* Fix incorrect VDLDoc
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-967
f:selectItems itemValue description incorrect.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-922 +
Remove maxlength from f:viewParam

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-998 +
Document that ui:fragment should not be bound to a bean with wider than
request scope, document that the type of the property must extend from
UIComponent.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-999 +
Changes to "template" attribute requiredness for ui:decorate and
ui:composition

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-901 +
Deprecate “targets” concept.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1088 +
add short-name to schema.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-746 +
Missing _method-signature_ element in taglib xsd.

===== Spec Clarifications

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1136 +
In _ExternalContext.dispatch()_ , clarify what is to be done if
_getRequestDispatcher()_ returns _null_ .

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1132 +
Replace literal strings with symbolic constants where possible.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1127 +
State Saving Serializability concerns.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1114 +
_javax.faces.view.facelets.Facelet.apply()_ spec version reference
error.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1100 +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1097 +
HTML5 id attribute sensitivity

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1064 +
In <<JSFMetadata.adoc#a7061,The
facelets-processing element>>, clarify that in XML and JSPX modes, only
the CDATA section start and end tags, not the entire CDATA section and
contents, should be consumed.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1063 +
_javax.faces.component.UIViewParameter.getSubmittedValue()_ return
value.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1058 +
ui:repeat tag size attribute

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1036 +
In <<UserInterfaceComponentModel.adoc#a911,
ValueExpression properties>>, clarify which attributes are expression
enabled,

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1035 +
Change section
<<Per-RequestStateInformation.adoc#a3300,FacesMessage>> to clarify the meaning of
having _FacesMessage_ instances on the _FacesContext._

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1026 +
f:ajax event attribute is String (not VE)

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1014
+
12.1.3
+
--
[none]
* The specification for the context-param that
declares the list of TagDecorator implementations to the runtime should
have always been javax.faces.FACELETS_DECORATORS. Prior to this
revision, the name of this context param was incorrectly specified as
javax.faces.DECORATORS. The reference implementation has always used the
correct name, however.
--

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1010 +
Check existing usages of the state saving method parameter to ensure
case insensitivity.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1004
+
M usingFacesInWebapps.fm
+
--
[none]
* 12.1.3 Set default for
javax.faces.FACELETS_BUFFER_SIZE to be 1024.
--

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-998 +
Additional clarification about binding attribute in VDLdocs

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-915 +
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1015 +
Non-normative text about http methods and prefix mapping

* http://java.net/jira/browse/JAVASERVERFACES-2740 +
In <<UserInterfaceComponentModel.adoc#a923,Component Bindings>>, clarify a corner
case regarding bean scope and component binding.

===== Resources

.Larger Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-809 +
This commit introduces a cleaner contract for allowing views to be
loaded from the Filesystem (including inside of JAR files). All VDL
resources must be loaded using ResourceHandler.createViewResource().

.Smaller Changes

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-996 +
Enable configuring the web app resources
directory. See <<UsingJSFInWebApplications.adoc#a6088,Application Configuration
Parameters>>.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-719 +
Method to map a viewId to a resourcePath

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1130-SerializeServerState +
Modify <<ApplicationIntegration.adoc#a4135,State Saving Alternatives and
Implications>> to clarify there is no requirement to serialize server
state by default when state saving method is server. Introduce a context
parameter to this effect in <<UsingJSFInWebApplications.adoc#a6088,Application
Configuration Parameters>>

===== Expression Language

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1092
+
Remove text from
MethodExpressionValueChangeListener and MethodExpressionActionListener
regarding wrapping any exception thrown by the invoked method being
wrapped in an AbortProcessingException. Such a requirement is incorrect
and should not have been introduced.
+
In section <<Per-RequestStateInformation.adoc#a3253,See
ExceptionHandler>>, add _AbortProcessingException_ , to the list of
exceptions that do not get to the _ExceptionHandler_ .

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1043 +
When publishing a ComponentSystemEvent, ensure the EL current component
is pushed correctly

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1164 +
If running in a container that supports EL 3.0, add the necessary
ELResolvers. See <<ExpressionLanguageAndManagedBeanFacility.adoc#a2966,See Stream, StaticField,
Map, List, Array, and Bean ELResolvers>>.

===== Configuration and Bootstrapping

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-533-ProgrammaticFacesConfig +
Modify <<UsingJSFInWebApplications.adoc#a6201,
Application Startup Behavior>> to account for requirement to call new API
when starting up.

===== Miscellaneous

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1169
+
New XML Namespace for XSD files introduced in
JSF 2.2, and also for facelet tag libraries.
+
The following XSD files are new for JSF 2.2,
and each will be in the XML namespace
_http://xmlns.jcp.org/xml/ns/javaee_ .
+
--
[none]
* _web-facelettaglibrary_2_2.xsd_

* _web-facesconfig_2_2.xsd_

* _web-partialresponse_2_2.xsd_
--
+
Facelet Tag Libraries will now respond to the
following URIs
+
--
[width="100%",cols="24%,38%,38%",options="header",]
|===
|Library |Old URI
|New URI
|Composite Components
|http://java.sun.com/jsf/composite a|
http://xmlns.jcp.org/jsf/composite



|Faces Core
|http://java.sun.com/jsf/core a|
http://xmlns.jcp.org/jsf/core



|HTML_BASIC
|http://java.sun.com/jsf/html a|
http://xmlns.jcp.org/jsf/html



|JSTL Core a|
http://java.sun.com/jsp/jstl/core



a|
http://xmlns.jcp.org/jsp/jstl/core



|JSTL Functions
|http://java.sun.com/jsp/jstl/functions a|
http://xmlns.jcp.org/jsp/jstl/functions



|Facelets Templating
|http://java.sun.com/jsf/facelets a|
http://xmlns.jcp.org/jsf/facelets



|Pass Through Attributes
|http://java.sun.com/jsf/passthrough a|
http://xmlns.jcp.org/jsf/passthrough



|Pass Through Elements
|http://java.sun.com/jsf a|
http://xmlns.jcp.org/jsf



|===
--
+
Developers are requested to use the values
from the New URI column, though both columns will work.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-997
+
M jsf-api/src/main/java/javax/faces/event/ComponentSystemEvent.java
+
--
[none]
* Override isAppropriateListener so that it
first asks the listener, "are you a ComponentSystemEventListener", then,
if not, asks super.isAppropriateListener()
--
+
M jsf-api/src/main/java/javax/faces/event/SystemEvent.java
+
--
[none]
* in isAppropriateListener(), document the
default implementation.
--
+
M jsf-api/src/main/java/javax/faces/component/UIComponent.java
+
--
[none]
* Make inner class
ComponentSystemEventListenerAdapter implement
ComponentSystemEventListener.
--

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-917
+
javax.faces.application.ResourceWrapper:
+
--
[none]
* getContentType()

* getLibraryName()

* getResourceName()

* setContentType(String)

* setLibraryName(String)

* setResourceName(String)
--
+
javax.faces.context.ExternalContextWrapper:
+
--
[none]
* getSessionMaxInactiveInterval()

* isSecure()

* setSessionMaxInactiveInterval()
--
+
javax.faces.context.PartialViewContextWrapper
+
--
[none]
* setPartialRequest(boolean)
--

* 12.1.3 add this text to the
javax.faces.STATE_SAVING_METHOD spec. When examining the value, the
runtime must ignore the case.

* Add
ExternalContext.getApplicationContextPath()
http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1012

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-787 +
restore ViewScope before templates are processed with buildView()

* 7.6.2.6 typo in spec for renderView(). Should be +
Return immediately if calling isRendered() on
the argument UIViewRoot returns false.

* Per Matt Benson, remove duplicate
descriptions of the cc and component implicit object from the getValue()
specification for the composite component ELResolver in section 5.6.2.1.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-869
+
Specify Cross Site Request Forgery
protection.
+
Add text in <<RequestProcessingLifecycle.adoc#a404,
Restore View>> to describe how non-postback requests are inspected for
protection, if necessary.
+
Remove text for writeState() in
<<RenderingModel.adoc#a4288,ResponseStateManager>>, point to the
JavaDocs.
+
Add View Protection methods to
<<ApplicationIntegration.adoc#a3874,Overview>> for ViewHandler.
+
Introduce subsections to
<<ApplicationIntegration.adoc#a3910,Default ViewHandler Implementation>> that
group the methods by their purpose. Add a new section
<<ApplicationIntegration.adoc#a3997,ViewHandler Methods that relate to View
Protection>>, which points to the javadocs. In
<<ApplicationIntegration.adoc#a3955,ViewHandler Methods Relating to
Navigation>>, in the spec for _getActionUrl()_ , specify how view
protection is affected.

* Remove tables in section
<<UsingJSFInWebApplications.adoc#a6598,Requirements for scanning of classes for
annotations>> +
The Javadoc tool lists annotations in a
separate section, making the tables that list JSF related annotations
redundant.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1082-DoctypeElement +
Add new section
<<FaceletsAndWebApplications.adoc#a5635,DOCTYPE and XML Declaration>>.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1141-SlashInResourceNames +
In <<RequestProcessingLifecycle.adoc#a758,Resource
Identifiers>>, declare that resourceName and resourceVersion, in addition
to the already listed other segments, are subject to the same
constraints.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1129-ResetValues +
In <<RequestProcessingLifecycle.adoc#a480,Render
Response Partial Processing>>, require calling _UIViewRoot.resetValues()_
if necessary.

==== Backward Compatibility with Previous Versions

Faces 2.2 is backwards compatible with Faces
2.1 and 2.0. This means that a web-application that was developed to run
with Faces 2.1 or 2.0 won’t require any modification when run with Faces
2.2 except in the cases described in the following section.

==== Breakages in Backward Compatibility

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-1092 +
Due to an error in previous versions of the
specification, exceptions were silently being swallowed that now will
bubble up to the exception handler. Code that was relying on this
incorrect behavior may need to be modified to account for fixing this
problem.

* http://java.net/jira/browse/JAVASERVERFACES_SPEC_PUBLIC-745
+
5.6.2.2 Table 5-11. Make the following
changes to the spec for Composite Component Attribute ELResoler
+
--
[none]
* Modify getType() according to new
specification language.

* Require the implementation of containsKey()
on the Map.

** containsKey(): If the attributes map contains
the key, return true. Otherwise, if a default value has been declared
for the attribute, return true. Otherwise, return false.
--
+
<<UserInterfaceComponentModel.adoc#a1671,
Composite Component Metadata>>
+
New text dealing with <cc:attribute>
+
--
[none]
* Any additional attributes on
_<composite:attribute/ >_ are exposed as attributes accessible from the
_getValue()_ and _attributeNames()_ methods on _PropertyDescriptor_ .
The return type from getValue() must be a _ValueExpression_ with the
exception of the _getValue(“type”)_ . The return type from
_getValue(“type”)_ must be _Class_ . If the value specified for the
_type_ attribute of _<cc:attribute/>_ cannot be converted to an actual
_Class_ , a _TagAttributeException_ must be thrown, including the _Tag_
and _TagAttribute_ instances in the constructor.
--

Yes, this is a backwards incompatible change,
but because the usecase is so specific, and the performance benefit so
substantial, it was judged to be worth the cost.




=== Changes between 2.0 Rev a and 2.1

==== <<FaceletsAndWebApplications.adoc#a5638,Facelet Tag Library mechanism>>

Document that the unprefixed namespace must
pass through.

==== New feature: <facelets-processing>

{empty}<<JSFMetadata.adoc#a7040,See
Required Handling of *-extension elements in the application
configuration resources files>>

==== Update schema for 2.1

The only new element is
<facelet-cache-factory>. See the full schema in the Javadoc section of
the documents.

==== Change Restore View Phase

Change <<RequestProcessingLifecycle.adoc#a404,See
Restore View>> to require a call to _ViewHandler.deriveLogicalViewId()_
before trying to find the _ViewDeclarationLanguage_ .

==== <<ApplicationIntegration.adoc#a3910,Default ViewHandler Implementation>>

Document _deriveLogicalViewId()._


=== Changes between 2.0 Final and 2.0 Rev a

==== Global changes

===== ExceptionQueuedEvent

The specification incorrectly refers to the
ExceptionQueuedEvent as the ExceptionEvent. All instances should be
replaced, as there is no such class ExceptionEvent in JSF.

===== Usage of the term "page" in the JSF 2.0 spec

This might be kind of nit-picky, but there
are several occurrences of the term "Facelet page" in the JSF 2.0 spec,
but I'd like to set forth the argument that the term "Facelet document"
or "Facelet view" would be more appropriate, depending on context.
Similarly, the spec uses the term "Composite component markup page"
which isn't always appropriate either. Better to call it a "Composite
component markup document" or something like that.

All Facelet XHTML files are documents, but
not all Facelet XHTML files are pages. There is a built-in bias to the
word "page" that assumes the markup output will be rendered as a "web
page" which is not always the case. In the case of portlets, the
rendered output is a fragment of markup (normally a <div>...</div>). In
the case of a custom renderkit, the rendered output might be some mobile
device. In the case of ICEfaces, the rendered markup is a server-side
DOM tree. In the case of a composite component, a Facelet XHTML file is
not a page, but a "Composite Component markup document" (or definition)
file.

For example.. Instead of a "Facelet Page", I
think the following should be called a "Facelet Document" or a "Facelet
View" (since the f:view tag is optional, but implied)

[source,xml]
----
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ez="http://java.sun.com/jsf/composite/ezcomp">
  <h:head>
    <title>A simple example of EZComp</title>
  </h:head>
  <h:body>
    <h:form>
    </h:form>
  </h:body>
</html>
----

But in the case of Portlets, the <html> ,
<head>, and <body> tags are forbidden. The equivalent "Facelet Document"
or "Facelet View" for portlets would look like this:

[source,xml]
----
<f:view xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:ez="http://java.sun.com/jsf/composite/ezcomp">
  ...
</f:view>
----

==== Front Matter

Change Sun logo to Oracle Logo. Sun postal
address to Oracle postal address, and Sun phone number to Oracle phone
number

Update spec license.

==== Chapter 2

===== <<RequestProcessingLifecycle.adoc#a404,Restore View>>

Per Andy Schwartz recommendation, loosen the
spec requirements for the delivery of the PostRestoreStateEvent to be
"somewhere during RestoreView".

===== <<RequestProcessingLifecycle.adoc#a584,Localized Application Messages>>

Suggestion: Change to

Validation Error: Length is less than
allowable minimum of 5.

===== <<RequestProcessingLifecycle.adoc#a710,JSR 303 Bean Validation>>

Change "leas" to "least"

===== <<RequestProcessingLifecycle.adoc#a710,JSR 303 Bean Validation>> needs to reference "Bean Validation Integration" section

While reading section 2.5.7, one becomes very
disappointed with the limited about of information that it provides. But
section 3.5.6 provides more information, so the recommendation is that
these sections reference each other, or perhaps are combined in some way
if that makes sense.

===== <<RequestProcessingLifecycle.adoc#a758,Resource Identifiers>>

Tighten spec for the localePrefix,
libraryName, and resourceVersion segments of the resource identifier.

==== Chapter 3

===== Clarify meaning of "javax.faces.bean" in <<UserInterfaceComponentModel.adoc#a1464,Bean Validator Activation>>

Section 3.5.6.1 says:

"If Bean Validation is present in the runtime
environment, the system must ensure that the javax.faces.Bean standard
validator is added with a call to Application.addDefaultValidatorId()"

But the reader of the Spec has no idea what
the "javax.faces.Bean" standard validator is, within the context of this
paragraph. Recommend adding some verbiage that says that
javax.faces.Bean is the validatorId of the standard JSR 303 validator of
the JSF 2.0 API, which equates to the
javax.faces.validator.BeanValidator class as mentioned in Section
10.4.1.4.

===== Need to be consistent between <<UserInterfaceComponentModel.adoc#a1393,Declarative Listener Registration>> of the JSF 2.0 Spec and the VDLDoc for f:event

Section 3.4.3.4 of the JSF 2.0 Spec reads:

The method signature for the MethodExpression
pointed to by the listener attribute must match the signature of

javax.faces.event.ComponentSystemEventListener.processEvent().

And the VDLDocs for f:event read:

(signature must match public void
listener(javax.faces.event.ComponentSystemEvent event) throws
javax.faces.event.AbortProcessingException)

Both of these are true, and indeed saying the
same thing. But I think it would be helpful to say BOTH things, in BOTH
documents.

===== Typo in <<UserInterfaceComponentModel.adoc#a1393,Declarative Listener Registration>> of the JSF 2.0 Spec regarding "beforeRender"

Section 3.4.3.4 of the JSF 2.0 Spec has this
example:

[source,xml]
----
<h:inputText value="#{myBean.text}">
  <f:event type="beforeRender" listener="#{myBean.beforeTextRender}" />
</h:inputText>
----

But "beforeRender" is a typo. The correct
value is "preRenderComponent" as stated in the f:event VDLDocs.

===== <<UserInterfaceComponentModel.adoc#a1419,Validation Registration>>, <<UserInterfaceComponentModel.adoc#a1518,What does it mean to be a JSF User Interface component?>>

Remove references to UInput.encodeEnd(). Not
for a very long time has this method been used to instigate validation.

===== <<UserInterfaceComponentModel.adoc#a1671,Composite Component Metadata>>

Section 3.6.2.1 of the Spec indicates that
the "hidden" property of the javax.bean.FeatureDescriptor is to appear
as an attribute for tags like composite:actionSource,
composite:attribute, composite:facet, and composite:interface but the
VDLDocs do not declare that the "hidden" property is available.

==== Chapter 4

===== <<StandardUserInterfaceComponents.adoc#a2268,Events>>

Remove text pertaining to
PostRestoreStateEvent, rely instead on text in setion 2.2.1.

==== Chapter 7

===== <<ApplicationIntegration.adoc#a3562,Overview>>

getNavigationCase should return
NavigationCase and not void.

===== <<ApplicationIntegration.adoc#a3571,Default NavigationHandler Algorithm>>

Add faces-include-view-params

===== <<ApplicationIntegration.adoc#a3910,Default ViewHandler Implementation>>

Fix typo the specified createView() should be
called in renderView() and restoreView().

==== Chapter 9

===== <<IntegrationWithJSP.adoc#a4654,<f:actionListener> >> of Spec PDF -- Missing "for" attribute of f:actionListener in Spec PDF

The example for f:selectItems includes a
noSelectionValue attribute, but that attribute isn't documented. VDLDocs
for f:selectItems does not document the noSelectionValue attribute.

Actually, it does document it, but it only
looks like it doesn't. It seems as though the itemLabelEscaped attribute
is documented twice, but really the second occurance is the
noSelectionValue.

===== <<IntegrationWithJSP.adoc.#a4654,<f:actionListener> >> and <<IntegrationWithJSP.adoc#a5282,<f:valueChangeListener> >>

Add this non-normative text.

Note that if the binding attribute is used,
the scope of the ValueExpression must be chosen carefully so as not to
introduce undesireable results. In general, when using the binding
attribute, do not point to beans in request or narrower scope.

==== Chapter 10

Need to change "confirm with" to "conform
with".

Confusing verbiage in table 10-1 of JSF 2.0
spec regarding the word "template"

In table 10-1, it correctly says that "page
templating" is not a feature of JSP.

But later on in the table, it says
"Expressions in template text cause unexpected behavior when used in
JSP."

Somehow there needs to be an explanation of
the distinction of "page templating" and "template text" here. Right now
it kind of reads as a contradiction.

===== <<FaceletsAndWebApplications.adoc#a5632,General Requirements>>

Add an assertion to section 10.3.1 stating
that EL expressions that appear in the facelet XHTML page must appear in
the rendered view as if they were the right hand side of the value
attribute of an at the same point in the page as the EL expression

===== <<FaceletsAndWebApplications.adoc#a5638,Facelet Tag Library mechanism>>

Section 10.3.2. Correct xref to point to
section in appendix that includes the facelet taglib schema.

Correct xref to point to section in appendix
that includes the facelet taglib schema.

===== VDLDocs and PDL documentation

<<FaceletsAndWebApplications.adoc#a6043,See
Facelet Templating Tag Library>>,
<<FaceletsAndWebApplications.adoc#a6043,See Facelet
Templating Tag Library>>, and <<FaceletsAndWebApplications.adoc#a6047,See JSTL Core
and Function Tag Libraries>> refer the reader to the "VDLDocs" for
Facelet, CC, and JSTL tag libraries respectively.

However, when one checks out the Mojarra
2.0.0 Beta 2 page, it talks about the "PDL" tag library documentation.
Also, when one clicks on the "PDL Documentation for Facelets2", it uses
the term "PDL" in several places.

So it looks like the View Declaration
Language (VDL) terminology hasn't made its way into the tag library docs
yet.

===== Possible error in section <<FaceletsAndWebApplications.adoc#a1111,<f:ajax> >> of the JSF 2.0 Spec regarding f:ajax and h:panelGrid

Section 10.4.1.1, shows this example:

[source,xml]
----
<f:ajax>
  <h:panelGrid>
    <h:inputText id=˝text1˝/>
    <h:commandButton id=˝button1˝/>
  </h:panelGrid>
</f:ajax>
----

And then has the following about the example:

<h:panelGrid> has no default event so in this
case a behavior would not be applied.

BUT the very next example is this:

[source,xml]
----
<f:ajax event=˝click˝>
  <h:panelGrid id=˝grid1˝>
    <h:inputText id=˝text1˝/>
    <h:commandButton id=˝button1˝>
      <f:ajax event=˝mouseover˝/>
    </h:commandButton>
  </h:panelGrid>
</f:ajax>
----

And then has the following comment:

From this example, grid1˝ and text1˝ would
have ajax behavior applied for an onclick˝ event

So... which is it? Does h:panelGrid get ajax
behavior or not? Can an HTML table have an "onclick" JavaScript event?

===== Redundant mentioning of Facelets in <<FaceletsAndWebApplications.adoc#a5828,<f:validateBean> >> of the JSF 2.0 Spec

Since the parent section (10.4.1) indicates
that sub-sections are Facelets-only in nature, then it is not necessary
to have (Facelets only) in the "Constraints" paragraph of Section
10.4.1.4 of the spec.

===== Availability of f:validateBean and f:validateRequired in JSP

<<FaceletsAndWebApplications.adoc#a5691,See Standard
Facelet Tag Libraries>> outlines the f: namespaced tags that are only
applicable to Facelets (and not JSP). In that section, f:validateBean,
and f:validateRequired are listed. However, they are both listed as
working with JSP as well (kind of like f:validateRegex), as can be seen
from the JSP TLDDocs.

According to Dan Allen: "those tags only work
partially in JSP. Yes, they work as single field validators. But the
branch validator capability does not work (wrapping the validator tag
around a branch). The later feature is Facelets only. So the validators
do have their feet in both ponds, but only Facelets has full support. I
suppose we could mention this tidbit in the JSP section."

Dan is correct that it should be mentoned in
the JSP section, but also, that f:validateBean and f:validateRequired
belong in both Section 10.4 and 9.4, with the limits of their
functionality described in each section.

==== Chapter 13

===== Redundancy in <<AjaxIntegration.adoc#a6831,Partial View Processing>> of the JSF 2.0 Spec

Section 13.4.2 of the JSF 2.0 spec has this
sentence:

The request contains special parameters that
indicate the request is a partial execute request or a partial execute
request that was triggered using Ajax

This needs clarification -- does this mean to
say:

partial execute request (not triggered by
Ajax) or a partial execute request (that was triggered using Ajax)

===== "Execute portions" of the JSF request processing lifecycle in the JSF 2.0 Spec

Section 13.4.2 reads:

Although the diagram in Section 13.4 Partial
View Traversal˝ depicts the execute˝ portion as encompassing everything
except the Render Response Phase˝, it really is the Apply Request Values
Phase˝, Update Model Values Phase˝ and Process Validations Phase˝.

Why does the diagram include the
INVOKE_APPLICATION phase if it's not "really" considered to be part of
the execute portions?

==== Chapter 14

===== <<JavaScriptAPI.adoc#a6856,Initiating an Ajax Request>> Typo in table 14.2.2 of the JSF 2.0 Spec

Table 14.2.2 reads:

"execute" phase

But in order to be consistent with the rest
of the spec, it should read:

"execute" portion

Also, the same goes for "render" in that the
word "portion" should be used instead of "phase".

===== <<JavaScriptAPI.adoc#a6933,Request/Response Event Handling>> Table 14.4.1

Change responseTxt to responseText.

Table 14.3: Reorder rows

==== Appendix A Metadata

Update schema to remove partial-traversal, as
well as fixing 768.

===== <<JSFMetadata.adoc.html#a7139,Deprecated DTD for Facelet Taglibraries Used by Versions of Facelets Prior to JSF 2.0>>

To ease migration for Facelet taglibraries
declared using pre-JSF 2.0 versions of Facelets, implementations must
support loading facelet taglibrary files that conform to the pre-JSF 2.0
Facelets DTD. Per DTD conventions, Facelet taglibrary files declare
conformance to this DTD by including text similar to the following in at
the top of their declaring file.

[source,xml]
----
<!DOCTYPE facelet-taglib PUBLIC
    "-//Sun Microsystems, Inc.//DTD Facelet Taglib 1.0//EN"
    "http://java.sun.com/dtd/facelet-taglib_1_0.dtd">
----

Use of this DTD is officially deprecated.
This DTD is included for reference in Section 1.2.1 "Deprecated DTD for
Facelet Taglibraries Used by Versions of Facelets Prior to JSF 2.0". It
is expected that proper JSF 2.0 Facelet Taglibraries will declare
conformance to the following schema, rather than the deprecated DTD.

==== VDLDoc changes

===== Typo in f:selectItems VDLDocs

Change "mest" to "must"

===== Need clarification on execute attribute of f:ajax

The VDLDocs for f:ajax say "Identifiers of
components" but, for some reason, it wasn't obvious to me that this term
referred to the "id" attributes of components. The recommendation isthat
this be clarified to say "list of <b>id</b> attribute values" instead.
Also, the value of an id attribute like "mycomponent" or something
should be added to an example that includes a keyword... something like
this: "@this componentone componenttwo"

===== Spelling error in VDLDocs for f:ajax

This one from Lincoln:

See the "onerror" attribute

There is an extra 'e' -> "oneerror"

===== Need clarification on required attribute in VDLDocs for tags that got a new "for" attribute in JSF 2.0

The VDLDocs correctly have green for the new
"for" attribute, but the "required" column says false, when that's not
always the case.

For example, with f:actionListener the
VDLDocs say that that it is not required. However, when the tag is used
as a child of a Composite Component, then the for attribute is indeed
required. This would be true of all tags like that, such as
f:convertDateTime, f:convertNumber, etc.

===== Uppercase typo in VDLDocs for f:event

Change uppercase "P" to lowercase for:
PostAddToView for the f:event VDLDocs

===== Need to change "JSP" to "Facelets" in "Body Content" of VDLDocs

Search for "JSP" on the f:event VDLDocs [1].
My suspicion is that this is a problem across the board.

===== Need clarification in VDLDocs for f:metadata

In the VDLDocs for f:metadata, recommend
changing:

"This tag must reside within the top level
XHTML file for the given viewId, not in a template"

to this:

"This tag must reside within the top level
Facelet view, or in a template-client, but not in a template"

Also, it needs to be clarified that the
page01.xhtml example is a template-client. So recommend changing this:

"viewId XHTML page, page01.xhtml"

to this:

"template-client XHTML page, page01.xhtml"

===== Missing description in VDLDocs for name attribute of f:viewParam

The VDLDocs for f:viewParam are missing
documentation of the "name" attribute, which is pretty important since
it is required.

===== VLDDocs on "for" attribute of f:viewParam claim it can be used in a CC

The VDLDocs for f:viewParam claim that the
"for" attribute is supported. I just checked Mojarra's jsf-api and
UIViewParameter.java does not support the "for" attribute, since it does
not have a getter/setter for "for" like HtmlOutputLabel does. There are
restrictions on f:viewParam such that it may only be used inside of
f:metadata, and f:metadata may only be used inside of f:view. So that
disqualifies the f:viewParam tag from being able to be used inside of a
Composite Component. Therefore I recommend that the documentation of the
"for" attribute be totally removed.

===== Miscellaneous VDLDoc items

* VDLDocs for "execute" attribute of f:ajax say
(must evaluate to java.lang.Object) but then say "Evaluates to
Collection"

* VDLDocs f:selectItem lists the new JSF 2.0
"noSelectionOption" but is not colored green to indicate "new in JSF
2.0" and the link for f:selectItem in the navigation frame needs to be
orange

* VDLDocs for f:validateBean should have all of
its attributes in green to indicate "new in JSF 2.0" since it is a new
tag.

* VDLDocs for f:validateRegex has a typo in the
description which reads "RegexpValidator" rather than "RegexValidator"

* In spec, the "Changes between 1.2 and EDR2"
section refers the reader to section 3.5.2 for the addition of
"javax.faces.RegularExpressionValidator" but actually it should be
section 3.5.5

* VDLDocs for h:button say that the outcome
attribute is not required, but really it should be required otherwise
there is no purpose of f:button -- you would end up navigating back to
the current view. The whole point of f:button is to perform navigation
to a different view that potentially contains view parameters. Why have
a bookmarkable URL back to itself?

* VDLDocs for h:button don't mention a disabled
attribute, but the h:link one does have the disabled attribute. My guess
would be that both should have this attribute?

* VDLDocs for h:outputScript and
h:outputStylesheet should indicate that even though the UIOutput class
implements the ValueHolder interface, the coverter and value attributes
are basically ignored by the renderers, since the value attribute has no
meaning. This is basically a design flaw -- a new class named
UIOutputResource should have been created instead of UIOutput being
reused.

* VDLDocs for h:outputScript and
h:outputStylesheet should indicate that the "name" attribute is
required, since section 2.6.1.3 implies that this is the case with the
following resource pattern:
[localePrefix/][libraryName/][libraryVersion/]resourceName[/resourceVersion]

* VDLDocs for h:outputScript needs to have all
the possible values for the target attribute documented. I think the
only valid values are "head", "body", and "form"

* VDLDocs for h:graphicImage has a dead
hyperlink to "Common Algorithm for Obtaining A Resource to Render

* VDLDocs for h:selectManyCheckbox indicate
orange for the collectionType and hideNoSelectionOption attributes but
they should be green to indicate "new in JSF 2.0"

* VDLDocs for h:selectManyCheckbox says that
the return type must evaluate to a String, but that's not entirely true.
It can also evaluate to a concrete class that implements
java.util.Collection

* VDLDocs for ui:param have two "name"
attributes specified. The second one should be the "value" attribute

===== Should TLDDocs now be VDLDocs?

The Spec introduces this term VDLDocs (which
as I said in the other email, was formerly PDLDocs), but it also refers
the reader to the TLDDocs. Should we just settle on VDLDocs as the
standard term throughout the Spec?

===== Typo in VDLDocs for f:event.

The VDLDocs for f:event specify a "name"
attribute, but the Description column of the page talks about a "type"
column (not "name"), which would be consistent with Section 3.4.3.4 of
the Spec which talks about a "type" column.

Jim Driscoll verified that there is a doc bug
in the VDLDocs for f:event and that the "name" attribute is actually
"type"

==== Accepted Changes from JCP Change Log for JSF 2.0 Rev a

The referenced spec public issue number can
be found in the issue tracker at +
https://javaserverfaces-spec-public.dev.java.net/servlets/ProjectIssues





[width="100%",cols="7%,10%,56%,15%,12%",]
|===
|ID |Category
|Description
|Fixed in Source Code Repository of
Specification |Issue

|C002 |Errata
|Section 5.6.2.2 is out of sync with the
current resolver implementation. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=848[Spec
Public:848]_

|C004 |Errata
|RenderKitDoc for _OutcomeTarget_ Renderers
are incorrect with respect to intended design. Refer to
_link:appendixB-changelog.html#UNKNOWN[]ChangeC006_ in the
footnotes section below. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=823[Spec
Public:823]_

|C007 |Errata
|Section JSF.11.4.7 Ordering. After the
sentence "The <others /> element must be handled as follows" add a
bullet point: "The <others /> element represents a set of application
configuration resources. This set is described as the set of all
application configuration resources discovered in the application minus
the one currently being processed, minus the application configuration
resources mentioned by name in the <ordering /> section. If this set is
the empty set, at the time the application configuration resources are
being processed, the <others > element must be ignored."
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=824[Spec
Public:824]_

|C008 |Errata
|taglib docs for composite:interface are
missing documentation for _componentType_ attribute.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=849[Spec
Public:849]_

|C011 |Errata
|Section JSF.3.6.2.1 Composite Component
Metadata Specification. Add _BehaviorHolderAttachedObjectTarget_ after
iii. _ActionSource2AttachedObjectTarget_ |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=825[Spec
Public:825]_

|C012 |Errata
|Javadocs for
_ResourceHandler.createResource(String resourceId)_ need to me ammended
to state that if there is an error in argument resourceId, null must be
returned by this method. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=851[Spec
Public:851]_

|C013 |Errata
|PDL DOCS: f:event listener attribute
clarification:Change description to: "A method expression that JSF
invokes when an event occurs. That event is specified with the name
attribute." |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=586[Spec
Public:586]_

|C015 |Errata
| _UIViewRoot.setBeforePhaseListeners()_
removed the statement that all phases including _RestoreView_ will have
their _beforePhaseListeners_ called. Reverted to the way it was in 1.2
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=826[Spec
Public:826]_

|C016 |Errata
|Section 2.6.2.1 Relocatable Resources: code
snippet: <f:view..../> should be <f:view...>
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=565[Spec
Public:565]_

|C017 |Errata
| _UISelectItem_ doesn't mention
_itemEscaped_ . |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=430[Spec
Public:430]_

|C018 |Errata
|
_ViewDeclarationLanguage.retargetAttachedObjects()_ misses talking about
Behaviors |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=827[Spec
Public:827]_

|C021 |Errata
|ui:insert missing existing "name" attribute,
implemented, tested, but not documented |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=667[Spec
Public:667]_

|C022 |Errata
| _f:valueChangeListener_ missing "for"
attribute. Implemented, tested, but not documented
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=828[Spec
Public:828]_

|C023 |Change
|in facelets VDLdoc, mark f:verbatim and
f:subview as deprecated |no
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=852[Spec
Public:852]_

|C024 |Errata
|Add an assertion to section 10.3.1 stating
that EL expressions that appear in the facelet XHTML page must appear in
the rendered view as if they were the right hand side of the value
attribute of an _<h:outputText>_ at the same point in the page as the EL
expression |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=829[Spec
Public:829]_

|C027 |Errata
|web-facelettaglibrary_2_0.xsd type incorrect
for composite-library-name. Should be ***javae:string***
|no |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=854[Spec
Public:854]_

|C028 |Errata
| _ui:remove_ VDLDoc has attribute with no
name |no |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=842[Spec
Public:842]_

|C029 |Errata
| _ui:param_ has attribute duplicated. One of
them should be "value" |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=855[Spec
Public:855]_

|C030 |Errata
|RenderKit Docs _javax.faces.CompositeFacet_
change " The implementation of _encodeBegin()_ , must obtain " to be "
The implementation of _encodeChildren()_ , must obtain "
|no |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=843[Spec
Public:843]_

|C031 |Errata
|VDL docs state that _composite:attribute_
has a target attribute with _required=true_ . This attribute is not
really required on _composite:attribute_ .
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=644[Spec
Public:644]_

|C032 |Errata
|Mention in spec that Objects put in view
scope may need to be Serializable |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=830[Spec
Public:830]_

|C033 |Errata
|Modify the javadoc for _ResourceHandler_ to
state that for resources residing at
_META-INF/resources/<resourceidentifier>_ . The implementation is not
required to support the optional _libraryVersion_ and _resourceVersion_
segments |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=844[Spec
Public:844]_

|C034 |Change
|Modify table 5-10 to state that implicit
object cc returns the current composite component, relative to the
composite component markup page in which the expression appears
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=831[Spec
Public:831]_

|C035 |Errata
|3.6.2.1 Modify composite component metadata
specification to state that, within the _cc:interface_ element, the
following attributes are not available unless _ProjectStage_ is
_Development_ : displayName, expert, hidden, preferred, shortDescription
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=832[Spec
Public:832]_

|C037 |Errata
| _UIComponent.restoreState()_ javadocs must
be changed to ***say*** NPE is thrown if context is null, but no action
is taken if state argument is null |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=845[Spec
Public:845]_

|C040 |Errata
|VDLDocs for _f:metadata_ . Don't mention
_f:view_ . State, "This tag must reside within the top level facelet
page whose filename corresponds ot the _viewid_ being loaded."
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=856[Spec
Public:856]_

|C043 |Errata
|Document _SEPARATOR_CHAR_ in section 11.1.3
where all the other context-params are documented
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=833[Spec
Public:833]_

|C044 |Errata
|Section 11.4.6 doesn't include
_ViewDeclarationLanguage_ , _VisitContextFactory_ ,
_ExceptionHandlerFactory_ , _PartialViewContext_ ,
_TagHandlerDelegateFactory_ as decoratable
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=834[Spec
Public:834]_

|C046 |Errata
|Section 10.4.1.1 specifies the use of
_AjaxBehaviors pushBehavior_ but _AjaxBehaviors_ is an implementation
detail (the class exists under com package)
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=836[Spec
Public:836]_

|C047 |Errata
|Add "defaults" for "execute", "render"
_AjaxBehavior_ in vdldocs. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=568[Spec
Public:568]_

|C048 |Errata
|JSP should not have _f:viewParam_ . Facelets
_f:viewParam_ must have _name_ attribute.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=656[Spec
Public:656]_

|C049 |Errata
|Spec section 3.2.5 is empty. Fix that
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=835[Spec
Public:835]_

|C050 |Errata
|Spec for _UIComponent.setParent()_
incomplete |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=837[Spec
Public:837]_

|C054 |Errata
| _f:event name_ attribute should be type.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=639[Spec
Public:639]_

|C058 |Errata
|Section 14.4.1: Table 14-4: responseTxt
should be responseText. Table 14-4: Add _status_ property; Table 14-4:
There is no "name" property. Table 14-3: reorder "status" values to be
in chronological order. Section 14.4.1.1: Fix use case.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=642[Spec
Public:642]_

|C060 |Change
|Replace the last sentence in the javadoc for
_FacesServlet.service()_ to say "The implementation must make it so
_FacesContext.release()_ is called within a finally block as late as
possible in the processing for the JSF related portion of this request".
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=846[Spec
Public:846]_

|C061 |Change
|Non-normatively document that JavaBeans
PropertyEditors will be used for EL Coercion. Mention this in the
context of JSF converters |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=838[Spec
Public:838]_

|C062 |Change
|In 3.1.5, explicitly mention not to use view
scope |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=839[Spec
Public:839]_

|C063 |Change
|7.4.1 Clarify that, in the case of
navigation actions, an empty string should be treated the same way as
null: stay on the same page. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=747[Spec
Public:747]_

|C064 |Change
|Correct _StateHolder.setTransient_ JavaDoc
(specified backwards) |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=840[Spec
Public:840]_

|C065 |Change
|Correct typos in _Composite.tld_ (for
pdldocs). Specifically, quotes around _actionListener_ ,
_method-signature_ (spelling). Also clarify the default value "false"
for "required" attribute. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=841[Spec
Public:841]_

|C066 |Change
|Specify that the Component Resource
container facet must be marked transient. Specifically, the JavaDocs for
_UIViewRoot.getComponentResources_ should include: "Set the transient
property of the facet to true." |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=800[Spec
Public:800]_

|C068 |Change
|Modify the facelet taglib xsd so that older
versions of taglibs are acceptable. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=744[Spec
Public:744]_

|C069 |Change
|Make sure vdldocs for _f:event_ list event
all possible event types |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=712[Spec
Public:712]_

|C072 |Errata
|Neither applyNextHandler of
DelegatingMetaTagHandler or nextHandler of TagHandler are documented.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=780[Spec
Public:780]_

|C073 |Errata
|Specify f:ajax execute/render id behavior in
vdldocs (as outlined in Section 10.4.1.1 of the spec).
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=567[Spec
Public:567]_

|C074 |Errata
|<view-param> has no business being a child
of <redirect> and should be renamed to <redirect-param>.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=698[Spec
Public:698]_

|C075 |Errata
|includeViewParams implicit navigation flag
should be faces-include-view-params. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=699[Spec
Public:699]_

|C077 |Errata
|Event broadcasting should apply to Behaviors
(not just ClientBehaviors). |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=798[Spec
Public:798]_

|C078 |Errata
|PostAddToViewEvent delivery specification
needs clarification. Clarify UIComponent.getParent and getChildren for
consistency. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=805[Spec
Public:805]_

|C079 |Errata
|RenderKit Docs - TableRenderer:Clarification
- the docs say to render the footer the same as the header which causes
the problem. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=255[Spec
Public:255]_

|C080 |Errata
|RenderKit Docs - ButtonRenderer Encode
behavior w/r/t onclick attribute - should not be passthrough attribute.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=257[Spec
Public:257]_

|C081 |Errata
|h:message "for" attribute is
mis-specified:"for" attribute should be relative id (not clientid).
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=266[Spec
Public:266]_

|C082 |Errata
|clarify whether expression of
binding-attribute of f:xxxxListener should be evaluated on postback.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=320[Spec
Public:320]_

|C083 |Errata
|Option rendering, specifically when dealing
with SelectItemGroups, is too generic. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=420[Spec
Public:420]_

|C084 |Errata
|submittedValue get/set methods
underspecified |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=434[Spec
Public:434]_

|C085 |Errata
|Current wording in renderkit docs leads to
double encoding of query parameters |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=436[Spec
Public:436]_

|C086 |Errata
|SelectManyCheckBox Clarification
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=466[Spec
Public:466]_

|C087 |Errata
|PDL document for JSTL(Facelets) has the
incorrect URI for the NameSpace. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=509[Spec
Public:509]_

|C088 |Errata
|API docs missing for ExceptionEventContext.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=515[Spec
Public:515]_

|C089 |Errata
|composite:attribute component documentation
for the attribute type should be for attribute method-signature.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=524[Spec
Public:524]_

|C090 |Errata
|The UML Diagram for javax.faces.event is out
of date. |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=525[Spec
Public:525]_

|C091 |Errata
|Minor typo in the Interface BehaviorHolder
API. |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=534[Spec
Public:534]_

|C092 |Errata
|Two references to the itemLabelEscaped
attribute. |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=56[Spec
Public:536]_

|C093 |Errata
|Missing class description for
javax.faces.event.PostValidateEvent and
javax.faces.event.PreValidateEvent. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=537[Spec
Public:537]_

|C094 |Errata
|Section 3.7.5 typo - ClientBehavorHolder
should be ClientBehaviorHolder. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=540[Spec
Public:540]_

|C095 |Errata
|Section 4.1.3 typo - NamingContaier should
be NamingContainer. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=541[Spec
Public:541]_

|C096 |Errata
|API Docs: Application.publishEvent: Docs say
to throw NPE if any of the arguments is null. However, sourceBaseType
arg can be null. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=553[Spec
Public:553]_

|C097 |Errata
|Facelets TLD Docs: Missing "for" attribute
for "message" and "messages" tags. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=558[Spec
Public:558]_

|C099 |Errata
|ResourceHandler docs: Clarify that relative
paths are disallowed in library names. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=577[Spec
Public:577]_

|C100 |Errata
|Renderkit Docs: h:link - Formatting - add
paragraphs |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=588[Spec
Public:588]_

|C101 |Errata
|Spec Section 2.5.9: Fix Grammar: "The first
client behavior to provided by the JSF specification is the
AjaxBehavior." should be: "The first client behavior provided by the JSF
specification is the AjaxBehavior." |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=590[Spec
Public:590]_

|C102 |Errata
|Spec Section 9.4 doesn't list all the
validation tags and it lists the validateDoubleRange tag twice.
|no |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=591[Spec
Public:591]_

|C103 |Errata
|Vdldocs and Spec section 3.6.2.1 have
component:actionSource target attribute with commas as delimiters -
should be "space" as delimiter. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=592[Spec
Public:592]_

|C104 |Errata
|Spec Section 7.4.1: getNavigationCase should
return NavigationCase and not void. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=605[Spec
Public:605]_

|C105 |Errata
|Spec Section 10.4.1.4 says: f:validateBean
should extend validateHandler. Should be ValidatorHandler.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=615[Spec
Public:615]_

|C106 |Errata
|Typo: Pages in the TLD docs says "JSF 2.0
Page Decraration Language". Should be "Declaration".
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=617[Spec
Public:617]_

|C107 |Errata
|Typos: Table 14-1, 14-2, page 14-3.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=629[Spec
Public:629]_

|C108 |Errata
|UIData.invokeOnComponent docs need to be
updated to include handling of column level facets.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=632[Spec
Public:632]_

|C109 |Errata
|Spec Section 3.5.6.1 needs to be corrected
to state that default validators are added during tag execution time.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=635[Spec
Public:635]_

|C110 |Errata
|validateBean and validateRequired tags need
to be removed from the JSP PDL documentation
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=645[Spec
Public:645]_

|C111 |Errata
|jsf.ajax.response update element
clarification needed in JavaScript docs. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=646[Spec
Public:646]_

|C112 |Errata
|Spec Section 10.4.1.1: Clarify what happens
when nesting and wrapping f:ajax tags collide.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=652[Spec
Public:652]_

|C113 |Errata
|Typo: Spec Section 8.3.1: "renderkit-id"
should be "render-kit-id" and "renderkit" should be "render-kit".
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=660[Spec
Public:660]_

|C114 |Errata
|Add "rendered" attribute to VDL docs for
ui:component and ui:fragment. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=661[Spec
Public:661]_

|C115 |Errata
|JavaDocs for UIComponent.processValidators
is incomplete. It should mention _popComponentFromEL_ .
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=664[Spec
Public:664]_

|C116 |Errata
|Dead link in VDL docs.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=666[Spec
Public:666]_

|C117 |Errata
|Spec Section 2.5.2.4: Standard messages for
LengthValidator are confusing. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=668[Spec
Public:668]_

|C118 |Errata
|Spec/pdldocs don't say what the default is
for "target" in h:outputScript. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=673[Spec
Public:673]_

|C119 |Errata
|partial-view-context-factory is only
mentioned in the schema part of the spec. Houls be added to Spec Section
13.4.2. |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=705[Spec
Public:705]_

|C120 |Errata
|Specification edits needed - see:
_http://docs.google.com/Doc?docid=0AW2H0u_g8JuTZGYycDZzdmhfMTRmOHo3ZmJncQ&hl=en[here]_
|no |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=714[Spec
Public:714]_

|C121 |Errata
|Typo - Spec Section 7.5.2: "ViewHanlder"
should be "ViewHandler"; "renderView" and "restoreView" methods should
call "ViewDeclarationLanguage.renderView" and
"ViewDeclarationLanguage.restoreView". |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=729[Spec
Public:729]_

|C122 |Errata
|Spec Section 2.6.1.3: Specify that a
libraryName or resourceName contains only XML NameChar, but not a colon;
a libraryName or resourceName does not match the regex
+++"[0-9]+(_[0-9]+)* or [A-Za-z]{2}(_[A-Za-z]{2}(_[A- Za-z]+)*)?"+++
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=740[Spec
Public:740]_

|C123 |Errata
|Typos in PDLDocs for ui:repeat
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=743[Spec
Public:743]_

|C124 |Errata
|Remove "partial-traversal" application
element from the spec as it does not exist in the schema.
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=767[Spec
Public:767]_

|C125 |Errata
|Add mssing ID attributes to schema for:
faces-config-orderingType,faces-config-ordering-orderingType,faces-config-absoluteOrderingType,faces-config-default-valueType,faces-config-from-view-idType,faces-config-client-behavior-rendererType,faces-config-behaviorType,faces-config-value-classType,faces-config-rendererType
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=768[Spec
Public:768]_

|C126 |Errata
|UIInput JavaDocs: Specify the handling of
conversion failures. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=775[Spec
Public:775]_

|C127 |Errata
|EditableValueHodler JavaDocs: Missing
"@Since 2.0" for "resetValue" method. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=779[Spec
Public:779]_

|C128 |Errata
|VDL documentation for f:selectItem
references the "escape" attribute. It should be "itemEscaped".
|yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=788[Spec
Public:788]_

|C129 |Errata
|Specify description for "f:param" "disabled"
attribute. |yes |
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=794[Spec
Public:794]_

|C130 |Errata
|Simplify PostRestoreStateEvent delivery
requirements. |yes
|
_https://javaserverfaces-spec-public.dev.java.net/issues/show_bug.cgi?id=806[Spec
Public:806]_
|===














=== Changes in versions below 2.0 Final

See the JavaServer Faces specification document for these changes. The change log items are removed from this
document in Jakarta Server Faces specification version 3.0.

