[[a6841]]
== JavaScript API

This chapter of the specification describes
the JavaScript functions that are used to facilitate Ajax operations in
a Jakarta Faces framework. All of these functions are contained in
the canonical _faces.js_ file.

[[a6844]]
=== Collecting and Encoding View State

In Jakarta Faces the
jakarta.faces.ViewState parameter was standardized to facilitate
“postback” requests to the server in a Jakarta Faces application.
Implementations must use this parameter to save the view state between
requests. Refer to the Javadocs for
jakarta.faces.render.ResponseStateManager.

Collecting and encoding view state that will
be sent to the server is a common operation used by most Jakarta
Faces Ajax frameworks. When a Jakarta Faces view is rendered, it will
contain a hidden field with the identifier jakarta.faces.ViewState whose
value contains the state for the current view. Jakarta Faces Ajax clients collect
additional view state, combine it with the current view state and send
it’s encoded form to the server.

[source,javascript]
----
faces.getViewState(FORM_ELEMENT)
----

Collect and encode element data for the given
FORM_ELEMENT and return it as the view state that will be sent to the
server. FORM_ELEMENT is the identifier for a DOM form element. All input
elements of type “hidden” should be included in the collection and
encoding process.

* Encode the name and value for each input
element of FORM_ELEMENT. Only select elements that have at least one of
their options selected must be included. only checkbox elements that are
checked must be included.

* Find the element identified as
jakarta.faces.ViewState in the specified FORM_ELEMENT and encode the name
and value.

* Return a concatenated String of the encoded
input elements and jakarta.faces.ViewState element.

[[a6852]]
==== Use Case

Collect and Encode Elements Of a Form

[source,javascript]
----
var viewState = faces.getViewState(form);
----


[[a6856]]
=== Initiating an Ajax Request

[source,javascript]
----
faces.ajax.request(source, |event|, { |OPTIONS| });
----

The faces.ajax.request function is responsible
for sending an Ajax request to the server. The
requirements for this function are as follows:

* The request must be sent asynchronously

* The request must be sent with method type
POST

* The request URL will be the form action
attribute

* All requests will be queued with the use of a
client side request queue to help ensure request ordering

[[a6864]]
==== Usage

Typically, this function is attached as a
JavaScript event listener.

[source,xml]
----
<ANY_HTML_OR_FACES_ELEMENT id="clientId" />
<script>
  document.getElementById('clientId').addEventListener(
    |EVENT|,
    function(event) {
      faces.ajax.request(source, event, { |OPTIONS| });
    }
  );
</script>
----

The _|EVENT|_ argument is the DOM event name such as “click”.

The function arguments are as follows:
_source_ is the DOM element that triggered this
Ajax request. It must be a DOM element object or a
string identifier for a DOM element. The _event_ argument is the
JavaScript event object. The optional _|OPTIONS|_ argument is a JavaScript
associative object array that may contain the following name/value
pairs:

[[a6871]]
.request OPTIONS
[%header, cols="2,8", frame="topbot", grid="rows", stripes="even"]
|===

| Name
| Value

| execute
| A space delimited list of client identifiers
or one of the keywords (<<a6884, Keywords>>).
These reference the components that will be processed during the
“execute” portion of the request processing lifecycle.

| render
| A space delimited list of client identifiers
or one of the keywords (<<a6884, Keywords>>).
These reference the components that will be processed during the
“render” portion of the request processing lifecycle.

| onevent
| A String that is the name of the JavaScript
function to call when an event occurs.

| onerror
| A String that is the name of the JavaScript
function to call when an error occurs.

| params
| An object that may include additional
parameters to include in the request.

|===

[[a6884]]
==== Keywords

The following keywords can be used for the
value of the “execute” and “render” attributes:

.Execute / Render Keywords
[%header, cols="3,7", frame="topbot", grid="rows", stripes="even"]
|===

| Keyword
| Description

| @all
| All component identifiers

| @none
| No identifiers

| @this
| The element that triggered the request

| @form
| The enclosing form

|===

[[a6897]]
==== Default Values

Values for the execute and render attributes
are not required. When using the JavaScript API, the default values for
execute is @this. The default value for render is @none.

[source,javascript]
----
faces.ajax.request(this, event)
----

is the same as:

[source,javascript]
----
faces.ajax.request(this, event, {execute:'@this', render:'@this'})
----

And, on a _<ANY_RENDERED_HTML_ELEMENT id="form:element">_

[source,javascript]
----
faces.ajax.request(this, event, {execute:'@this'})
----

is the same as:

[source,javascript]
----
faces.ajax.request(this, event, {execute:'form:element'})
----

Refer to the VDLDocs on the _f:_ tag library
for the default values for the execute and render attributes
when they are used with the core “<f:ajax>” tag.

[[a6911]]
==== Request Sending Specifics

The mechanics of sending an Ajax request
becomes very important to promote component compatability. Even more
important, is standardizing on the post data that is sent to server
implementations, so they all can expect the same arguments.
The request header must be set with the name
Faces-Request and the value partial/ajax. Specifics of formulating post
data and sending the request must be followed as outlined in the
JavaScript documentation for the faces.ajax.request function. The post
data arguments that must be sent are:

[%header, cols="3,7", frame="topbot", grid="rows", stripes="even"]
|===
|Name |Value

|jakarta.faces.ViewState
|The value of the jakarta.faces.ViewState
hidden field. This is included when using the faces.getViewState function.

|jakarta.faces.partial.ajax
|true

|jakarta.faces.source
|The identifier of the element that is the
source of this request
|===

[[a6921]]
==== Use Case

[source,javascript]
----
faces.ajax.request(this, event, {execute:'@this', render:'outtext'})
----

This use case assumes there is another
component in the view with the identifier _outtext_.

[source,xml]
----
<h:outputText id="outtext" value="#{bean.text}" />
----

[[a7017]]
=== Processing The Ajax Response

[source,javascript]
----
faces.ajax.response(request, context);
----

The faces.ajax.response function is
called when a request completes successfully. This typically means that
returned status code is >= 200 and < 300. The faces.ajax.response function
must extract the XML response from the request argument. The XML
response is expected to follow the format that is outlined in the
JavaScript documentation for this function. The response format is an
“instruction set” telling this function how it should update the DOM.
The context argument contains properties that facilitate event and error
processing such as the source DOM element (the DOM element that
triggered the Ajax request), onevent (the event handling callback for
the request) and onerror (the error handling callback for the request).
The specifics details of this function’s
operation must follow the faces.ajax.response JavaScript
documentation.


[[a6931]]
=== Registering Callback Functions

The JavaScript API allows you to register
callback functions for Ajax request/response event monitoring and error
handling. The event callbacks become very useful when monitoring request
connection status. The error callback provides a convenient way for
implementations to trap errors. The handling of the errors is left up to
the implementation. These callback function names can also be set using
the JavaScript API (<<a6871, request
OPTIONS>>), and the core <f:ajax> tag.

[[a6933]]
==== Request/Response Event Handling

[source,javascript]
----
faces.ajax.addOnEvent(callback);
----

The callback argument must be a reference to
an existing JavaScript function that will handle the events. The events
that can be handled are:

[[a6936]]
.Events
[%header, cols="3,7", frame="topbot", grid="rows", stripes="even"]
|===

| Event Name
| Description

| begin
| Occurs immediately before the request is
sent.

| complete
| Occurs immediately after the request has
completed. For successful requests, this is immediately before
jakarta.faces.response is called. For unsuccessful requests, this is
immediately before the error handling callback is invoked.

| success
| Occurs immediately after faces.ajax.response
has completed.

|===

The callback function has access to the
following “data payload”:.

[[a6947]]
.Event Data Payload
[%header, cols="3,7", frame="topbot", grid="rows", stripes="even"]
|===

| Name
| Description/Value

| type
| “event”

| status
| One of the events specified in <<a6936, Events>>

| source
| The DOM element that triggered the Ajax request.

| responseCode
| Ajax request object ‘status’
(XMLHttpRequest.status); Not present for “begin” event;

| responseXML
| The XML response
(XMLHttpRequest.responseXML); Not present for “begin” event;

| responseText
| The text response
(XMLHttpResponse.responseText) Not present for “begin” event;

|===

[[a6962]]
===== Use Case

An event listener can be installed from
JavaScript in this manner.

[source,javascript]
----
function statusUpdate(data) {
  // do something with data.status or other parts of data payload
}
...
faces.ajax.addOnEvent(statusUpdate);
----

An event listener can be installed from
markup in this manner.

[source,xml]
----
<f:ajax ... onevent="statusUpdate" />
----

[[a6973]]
==== Error Handling

[source,javascript]
----
faces.ajax.addOnError(callback);
----

The callback argument must be a reference to
an existing JavaScript function that will handle errors from the server.

[[a6976]]
.Errors
[%header, cols="3,7", frame="topbot", grid="rows", stripes="even"]
|===

| Error Name
| Description

| httpError
| request status==null or
request.status==undefined or request.status<200 or request.status >=300

| serverError
| The Ajax response contains an “error” element.

| malformedXML
| The Ajax response does not follow the
proper format.

| emptyResponse
| There was no Ajax response from the server.

|===

The callback function has access to the
following “data payload”:.

[[a6988]]
.Error Data Payload
[%header, cols="3,7", frame="topbot", grid="rows", stripes="even"]
|===

| Name
| Description/Value

| type
| “error”

| status
| One of error names defined <<a6976, Errors>>

| description
| Text describing the error

| source
| The DOM element that triggered the Ajax request.

| responseCode
| Ajax request object ‘status’ (XMLHttpRequest.status);

| responseXML
| The XML response (XMLHttpRequest.responseXML)

| responseText
| The text response (XMLHttpResponse.responseTxt)

| errorName
| The error name taken from the Ajax response “error” element.

| errorMessage
| The error messages taken from the Ajax response “error” element.

|===

[[a7009]]
===== Use Case

[source,javascript]
----
faces.ajax.addOnError(handleError);
...
var handleError = function handleError(data) {
  ... do something with “data payload” ...
}
----




=== Determining An Application’s Project Stage

[source,javascript]
----
faces.getProjectStage();
----

This function must
return the constant representing the current state of the running
application in a typical product development lifecycle. The returned
value must be the value returned from the server side method
jakarta.faces.application.Application.getProjectStage(); Refer to
<<a3455, ProjectStage Property>> for more details
about this property.

[[a7020]]
==== Use Case

[source,javascript]
----
var projectStage = faces.getProjectStage();
if (projectStage == "Production") {
  .... throw exception
} else if (projectStage == "Development") {
  .... send an alert for debugging
}
----




[[a7029]]
=== Script Chaining

[source,javascript]
----
faces.util.chain(source, event, |<script>, <script>,...| )
----

This utility function invokes an arbitrary
number of scripts in sequence. If any of the scripts return false,
subsequent scripst will not be executed. The arguments are:

* source - The DOM element that triggered this
Ajax request, or an id string of the element to use as the triggering
element.

* event - The DOM event that triggered this
Ajax request. A value does not have to be specified for this argument.

The variable number of script arguments
follow the source and event arguments. Refer to the JavaScript API
documentation in the source for more details.

