== Per-Request State Information

During request processing for a JSF page, a
context object is used to represent request-specific information, as
well as provide access to services for the application. This chapter
describes the classes which encapsulate this contextual information.

[[a3091]]
=== FacesContext

JSF defines the
_jakarta.faces.context.FacesContext_ abstract base class for representing
all of the contextual information associated with processing an incoming
request, and creating the corresponding response. A _FacesContext_
instance is created by the JSF implementation, prior to beginning the
request processing lifecycle, by a call to the _getFacesContext_ method
of _FacesContextFactory_ , as described in
<<Per-RequestStateInformation.adoc#a3366,See FacesContextFactory>>. When the request
processing lifecycle has been completed, the JSF implementation will
call the _release_ method, which gives JSF implementations the
opportunity to release any acquired resources, as well as to pool and
recycle _FacesContext_ instances rather than creating new ones for each
request.

[[a3096]]
=== Application

[width="100%",cols="100%",]
|===
|public Application getApplication();
|===

{empty}[P1-start-application]The JSF
implementation must ensure that the _Application_ instance for the
current web application is available via this method, as a convenient
alternative to lookup via an _ApplicationFactory_ .[P1-end]

=== Attributes

[width="100%",cols="100%",]
|===
|public Map<Object,Object> getAttributes();
|===

{empty}[P1-start-attributes]Return a mutable
_Map_ representing the attributes associated wth this _FacesContext_
instance. This _Map_ is useful to store attributes that you want to go
out of scope when the Faces lifecycle for the current request ends,
which is not always the same as the request ending, especially in the
case of _Servlet_ filters that are invoked after the Faces lifecycle for
this request completes. Accessing this _Map_ does not cause any events
to fire, as is the case with the other maps: for request, session, and
application scope.[P1-end]

[[a3099]]
=== ELContext

[width="100%",cols="100%",]
|===
|public ELContext getELContext();
|===

Return the _ELContext_ instance for this
_FacesContext_ instance. This _ELContext_ instance has the same lifetime
and scope as the _FacesContext_ instance with which it is associated,
and may be created lazily the first time this method is called for a
given _FacesContext_ instance. [P1-start-elcontext]Upon creation of the
ELContext instance, the implementation must take the following action:

Call the
_ELContext.putContext(java.lang.Class, java.lang.Object)_ method on the
instance, passing in _FacesContext.class_ and the _this_ reference for
the _FacesContext_ instance itself.

{empty}If the _Collection_ returned by
_jakarta.faces.Application.getELContextListeners()_ is non-empty, create
an instance of _ELContextEvent_ and pass it to each _ELContextListener_
instance in the _Collection_ by calling the
_ELContextListener.contextCreated(jakarta.el.ELContextEvent)_
method.[P1-end]

=== ExternalContext

{empty}It is sometimes necessary to interact
with APIs provided by the containing environment in which the Jakarta Server
Faces application is running. In most cases this is the servlet API, but
it is also possible for a Jakarta Server Faces application to run inside of
a portlet. Jakarta Server Faces provides the _ExternalContext_ abstract
class for this purpose. [P1-start-externalContext]This class must be
implemented along with the _FacesContext_ class, and must be accessible
via the _getExternalContext_ method in _FacesContext_ .[P1-end]

[width="100%",cols="100%",]
|===
|public ExternalContext getExternalContext();
|===

{empty}[P1-start externalContext during Init]
The default implementation must return a valid value when this method is
called during startup time. See the javadocs for this method for the
complete specification. [P1-end]

The _ExternalContext_ instance provides
immediate access to all of the components defined by the containing
environment (servlet or portlet) within which a JSF-based web
application is deployed. The following table lists the container objects
available from _ExternalContext_ . Note that the Access column refers to
whether the returned object is mutable. None of the properties may be
set through _ExternalContext_ . itself.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Name |Access
|Type |Description
| _applicationMap_
|RW |
_java.util.Map_ |The application context
attributes for this application.

| _authType_ |RO
| _String_ |The
method used to authenticate the currently logged on user (if any).

| _context_ |RW
| _Object_ |The
application context object for this application.

| _initParameterMap_
|RO |
_java.util.Map_ |The context initialization
parameters for this application

| _remoteUser_ |RO
| _String_ |The
login name of the currently logged in user (if any).

| _request_ |RW
| _Object_ |The
request object for this request.

| _requestContextPath_
|RO | _String_
|The context path for this application.

| _requestCookieMap_
|RO |
_java.util.Map_ |The cookies included with
this request.

| _requestHeaderMap_
|RO |
_java.util.Map_ |The HTTP headers included
with this request (value is a String).

| _requestHeaderValuesMap_
|RO |
_java.util.Map_ |.The HTTP headers included
with this request (value is a String array).

| _requestLocale_
|RW |
_java.util. +
Locale_ |The preferred Locale for this
request.

| _requestLocales_
|RW |
_java.util. +
Iterator_ |The preferred Locales for this
request, in descending order of preference.

| _requestMap_ |RW
| _java.util.Map_
|The request scope attributes for this
request.

| _requestParameterMap_
|RO |
_java.util.Map_ |The request parameters
included in this request (value is a String).

| _requestParameterNames_
|RO | _Iterator_
|The set of request parameter names included
in this request.

| _requestParameterValuesMap_
|RO |
_java.util.Map_ |The request parameters
included in this request (value is a String array).

| _requestPathInfo_
|RO | _String_
|The extra path information from the request
URI for this request.

| _requestServletPath_
|RO | _String_
|The servlet path information from the
request URI for this request.

| _response_ |RW
| _Object_ |The
response object for the current request.

| _sessionMap_ |RW
| _java.util.Map_
|The session scope attributes for this
request<<a9087,5>>.

| _userPrincipal_
|RO |
_java.security.Principal_ |The Principal
object containing the name of the currently logged on user (if any).
|===

See the JavaDocs for the normative
specification.

=== Flash

The _Flash_ provides a way to pass temporary
objects between the user views generated by the faces lifecycle.
Anything one places in the flash will be exposed to the next view
encountered by the same user session and then cleared out..

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Name |Access
|Type |Description
| _flash_ |R
| _Flash_ |See the
javadocs for the complete specification.
|===



=== ViewRoot

[width="100%",cols="100%",]
|===
a|
public UIViewRoot getViewRoot();



public void setViewRoot(UIViewRoot root);

|===

During the _Restore View_ phase of the
request processing lifecycle, the state management subsystem of the JSF
implementation will identify the component tree (if any) to be used
during the inbound processing phases of the lifecycle, and call
_setViewRoot()_ to establish it.

=== Message Queue

[width="100%",cols="100%",]
|===
|public void addMessage(String clientId,
FacesMessage message);
|===

During the _Apply Request Values_ , _Process
Validations_ , _Update Model Values_ , and _Invoke Application_ phases
of the request processing lifecycle, messages can be queued to either
the component tree as a whole (if _clientId_ is _null_ ), or related to
a specific component based on its client identifier.

[width="100%",cols="100%",]
|===
a|
public Interator<String>
getClientIdsWithMessages();



public Severity getMaximumSeverity();



public Iterator<FacesMessage>
getMessages(String clientId);



public Iterator<FacesMessage> getMessages();

|===

[P1-start-messageQueue]The
_getClientIdsWithMessages()_ method must return an _Iterator_ over the
client identifiers for which at least one _Message_ has been queued.
This method must be implemented so the clientIds are returned in the
order of calls to _addMessage().[P1-end]_ The _getMaximumSeverity()_
method returns the highest severity level on any _Message_ that has been
queued, regardless of whether or not the message is associated with a
specific client identifier or not. The _getMessages(String)_ method
returns an _Iterator_ over queued _Message_ s, either those associated
with the specified client identifier, or those associated with no client
identifier if the parameter is _null_ . The _getMessages()_ method
returns an _Iterator_ over all queued _Messages_ , whether or not they
are associated with a particular client identifier. Both of the
_getMessage()_ variants must be implemented such that the messages are
returned in the order in which they were added via calls to
_addMessage()_ .

For more information about the _Message_
class, see <<Per-RequestStateInformation.adoc#a3300,See FacesMessage>>.

=== RenderKit

[width="100%",cols="100%",]
|===
|public RenderKit getRenderKit();
|===

Return the _RenderKit_ associated with the
render kit identifier in the current _UIViewRoot_ (if any).


[[a3198]]
=== ResponseStream and ResponseWriter

[width="100%",cols="100%",]
|===
a|
public ResponseStream getResponseStream();



public void setResponseStream(ResponseStream
responseStream);



public ResponseWriter getResponseWriter();



public void setResponseWriter(ResponseWriter
responseWriter);



public void enableResponseWriting(boolean
enable);

|===

JSF supports output that is generated as
either a byte stream or a character stream. _UIComponent_ s or
_Renderer_ s that wish to create output in a binary format should call
_getResponseStream()_ to acquire a stream capable of binary output.
Correspondingly, _UIComponent_ s or _Renderer_ s that wish to create
output in a character format should call _getResponseWriter()_ to
acquire a writer capable of character output.

Due to restrictions of the underlying servlet
APIs, either binary or character output can be utilized for a particular
response—they may not be mixed.

Please see <<ApplicationIntegration.adoc#a3871,See
ViewHandler>> to learn when _setResponseWriter()_ and
_setResponseStream()_ are called.

The enableResponseWriting method is useful to
enable or disable the writing of content to the current _ResponseWriter_
instance in this FacesContext. [P1-start-enableWriting]If the enable
argument is false, content should not be written to the response if an
attempt is made to use the current _ResponseWriter._

=== Flow Control Methods

[width="100%",cols="100%",]
|===
a|
public void renderResponse();



public void responseComplete();



public boolean getRenderResponse();



public boolean getResponseComplete();

|===

Normally, the phases of the request
processing lifecycle are executed sequentially, as described in
<<RequestProcessingLifecycle.adoc#a369,See Request Processing Lifecycle>>.” However,
it is possible for components, event listeners, and validators to affect
this flow by calling one of these methods.

The _renderResponse()_ method signals the JSF
implementation that, at the end of the current phase (in other words,
after all of the processing and event handling normally performed for
this phase is completed), control should be transferred immediately to
the _Render Response_ phase, bypassing any intervening phases that have
not yet been performed. For example, an event listener for a tree
control that was designed to process user interface state changes (such
as expanding or contracting a node) on the server would typically call
this method to cause the current page to be redisplayed, rather than
being processed by the application.

The _responseComplete()_ method, on the other
hand, signals the JSF implementation that the HTTP response for this
request has been completed by some means other than rendering the
component tree, and that the request processing lifecycle for this
request should be terminated when the current phase is complete. For
example, an event listener that decided an HTTP redirect was required
would perform the appropriate actions on the response object (i.e.
calling _ExternalContext.redirect()_ ) and then call this method.

{empty}In some circumstances, it is possible
that both _renderResponse()_ and _responseComplete()_ might have been
called for the request. [P1-start-flowControl]In this case, the JSF
implementation must respect the _responseComplete()_ call (if it was
made) before checking to see if _renderResponse()_ was called.[P1-end]

The _getRenderResponse()_ and
_getResponseComplete()_ methods allow a JSF-based application to
determine whether the renderResponse() or responseComplete() methods,
respectively, have been called already for the current request.

[[a3225]]
=== Partial Processing Methods



[width="100%",cols="100%",]
|===
|public PartialViewContext
getPartialViewContext();
|===

{empty}[P1-start-getpartialViewContext]The
getPartialViewContext()method must return an instance of
PartialViewContext either by creating a new instance, or returning an
existing instance from the FacesContext.[P1-end-getpartialViewcontext]

[[a3229]]
=== Partial View Context

The PartialViewContext contains the
constants, properties and methods to facilitate partial view processing
and partial view rendering. Refer to
<<AjaxIntegration.adoc#a6831,See Partial View
Processing>> and <<AjaxIntegration.adoc#a6833,See
Partial View Rendering>>. Refer to the JavaDocs for the
jakarta.faces.context.PartialViewContext class for method requirements.

[[a3231]]
=== Access To The Current FacesContext Instance

[width="100%",cols="100%",]
|===
a|
public static FacesContext
getCurrentInstance();



protected static void
setCurrentInstance(FacesContext context);

|===

{empty}Under most circumstances, JSF
components, and application objects that access them, are passed a
reference to the _FacesContext_ instance for the current request.
However, in some cases, no such reference is available. The
_getCurrentInstance()_ method may be called by any Java class in the
current web application to retrieve an instance of the _FacesContext_
for this request. [P1-start-currentInstance]The JSF implementation must
ensure that this value is set correctly before _FacesContextFactory_
returns a _FacesContext_ instance, and that the value is maintained in a
thread-safe manner.[P1-end]

{empty}[P1-start facesContextDuringInit] The
default implementation must allow this method to be called during
application startup time, before any requests have been serviced. If
called during application startup time, the instance returned must have
the special properties as specified on the javadocs for
_FacesContext.getCurrentInstance()_ The . [P1-end]

[[a3237]]
=== CurrentPhaseId

The default lifecycle implementation is
responsible for setting the _currentPhaseId_ property on the
_FacesContext_ instance for this request, as specified in
<<RequestProcessingLifecycle.adoc#a401,See Standard Request Processing Lifecycle
Phases>>. The following table describes this property.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Name |Access
|Type |Description
| _currentPhaseId_
|RW | _PhaseId_
|The _PhaseId_ constant for the current phase
of the request processing lifecycle __
|===

=== ExceptionHandler

The _FacesContextFactory_ ensures that each
newly created _FacesContext_ instance is initialized with a fresh
instance of _ExceptionHandler_ , created from _ExceptionHandlerFactory_
.The following table describes this property.

[width="100%",cols="25%,25%,25%,25%",options="header",]
|===
|Name |Access
|Type |Description
| _exceptionHandler_
|RW |
_ExceptionHandler_ |Set by
_FacesContextFactory.getFacesContext()_ , this class is the default
exception handler for any unexpected Exceptions that happen during the
Faces lifecycle. See the Javadocs for _ExceptionHandler_ for details.
|===

Please see <<LifecycleManagement.adoc#a6635,See
PhaseListener>> for the circumstances under which _ExceptionHandler_ is
used.


[[a3253]]
=== ExceptionHandler

 _ExceptionHandler_ is the central point for
handling _unexpected_ _Exceptions_ that are thrown during the Faces
lifecycle. The _ExceptionHandler_ must _not_ be notified of any
_Exceptions_ that occur during application startup or shutdown.

Several places in the Faces specification
require an _Exception_ to be thrown as a result of normal lifecycle
processing. [P1-start_expected_exceptions]The following expected
_Exception_ cases must not be handled by the ExceptionHandler.

All cases where a _ValidatorException_ is
specified to be thrown or caught

All cases where a _ConverterException_ is
specified to be thrown or caught

The case when a MissingResourceException is
thrown during the processing of the _<f:loadBundle />_ tag.

If an exception is thrown when the runtime is
processing the _@PreDestroy_ annotation on a managed bean.

All classes when an
_AbortProcessingException_ is thrown.

All other _Exception_ cases must not be
swallowed, and must be allowed to flow up to the _Lifecycle.execute_ ()
method where the individual lifecycle phases are implemented.
[P1-end_expected_exceptions] At that point, all _Exceptions_ are passed
to the _ExceptionHandler_ as described in
<<LifecycleManagement.adoc#a6635,See PhaseListener>>.

Any code that is not a part of the core Faces
implementation may leverage the _ExceptionHandler_ in one of two ways.

=== Default ExceptionHandler implementation

The default ExceptionHandler must implement
the following behavior for each of its methods

[width="100%",cols="100%",]
|===
|public ExceptionQueuedEvent
getHandledExceptionEvent();
|===

Return the first “handled”
_ExceptionQueuedEvent_ , that is, the one that was actually re-thrown.

[width="100%",cols="100%",]
|===
|public Iterable<ExceptionQueuedEvent>
getHandledExceptionEvents();
|===

The default implementation must return an
_Iterable_ over all _ExceptionEvents_ that have been handled by the
_handle()_ method.

[width="100%",cols="100%",]
|===
|public Throwable getRootCause(Throwable t);
|===

Unwrap the argument _t_ until the unwrapping
encounters an _Object_ whose _getClass()_ is not equal to
_FacesException.class_ or _jakarta.el.ELException.class_ . If there is no
root cause, _null_ is returned.

[width="100%",cols="100%",]
|===
|public Iterable<ExceptionQueuedEvent>
getUnhandledExceptionEvents();
|===

Return an _Iterable_ over all
_ExceptionEvents_ that have not yet been handled by the _handle()_
method.

[width="100%",cols="100%",]
|===
|public void handle() throws FacesException;
|===

Inspect all unhandled _ExceptionQueuedEvent_
instances in the order in which they were queued by calls to
_Application.publishEvent(ExceptionQueuedEvent.class, eventContext)_ .

For each _ExceptionQueuedEvent_ in the list,
call its _getContext()_ method and call _getException()_ on the returned
result. Upon encountering the first such _Exception_ the corresponding
_ExceptionQueuedEvent_ must be set so that a subsequent call to
_getHandledExceptionEvent()_ or _getHandledExceptionEvents()_ returns
that _ExceptionQueuedEvent_ instance. The implementation must also
ensure that subsequent calls to _getUnhandledExceptionEvents()_ do not
include that _ExceptionQueuedEvent_ instance. Let _toRethrow_ be either
the result of calling _getRootCause()_ on the _Exception_ , or the
_Exception_ itself, whichever is non- _null_ . Re-wrap _toThrow_ in a
_ServletException_ or ( _PortletException_ , if in a portlet
environment) and throw it, allowing it to be handled by any
_<error-page>_ declared in the web application deployment descriptor or
by the default error page as described elsewhere in this section.

There are two exceptions to the above
processing rules. In both cases, the _Exception_ must be logged and not
re-thrown.

If an unchecked _Exception_ occurs as a
result of calling a method annotated with _PreDestroy_ on a managed
bean.

If the _Exception_ originates inside the
_ELContextListener.removeElContextListener()_ method __

The _FacesException_ must be thrown if and
only if a problem occurs while performing the algorithm to handle the
_Exception_ , not as a means of conveying a handled Exception itself.

[width="100%",cols="100%",]
|===
|public boolean isListenerForSource(Object
source);
|===

The default implementation must return _true_
if and only if the source argument is an instance of
_ExceptionEventContext_ .

[width="100%",cols="100%",]
|===
|public void processEvent(SystemEvent
ExceptionQueuedEvent) throws AbortProcessingException;
|===

The default implementation must store the
argument _ExceptionQueuedEvent_ in a strongly ordered queue for later
processing by the _handle()_ method. __

=== Backwards Compatible ExceptionHandler

[P1-startPreJsf2ExceptionHandler]The runtime
must provide an _ExceptionHandlerFactory_ implementation with the fully
qualified java classname of
_jakarta.faces.webapp.PreJsf2ExceptionHandlerFactory_ that creates
_ExceptionHandler_ instances that behave exactly like the default
_ExceptionHandler_ except that the _handle()_ method behaves as follows.

Versions of JSF prior to 2.0 stated in
<<LifecycleManagement.adoc#a6635,See PhaseListener>> “Any exceptions thrown
during the _beforePhase()_ listeners must be caught, logged, and
swallowed...Any exceptions thrown during the _afterPhase()_ liseteners
must be caught, logged, and swallowed.” The _PreJsf2ExceptionHandler_
restores this behavior for backwards compatibilty.

{empty}The implementation must allow users to
install this _ExceptionHandlerFactory_ into the application by nesting
_<exception-handler-factory>jakarta.faces.webapp.PreJsf2ExceptionHandlerFactory</exception-handler-factory>_
inside the <factory> element in the application configuration
resource.[P1-endPreJsf2ExceptionHandler]

=== Default Error Page

If no _<error-page>_ elements are declared in
the web application deployment descriptor, the runtime must provide a
default error page that contains the following information.

The stack trace of the _Exception_

The _UIComponent_ tree at the time the
_ExceptionQueuedEvent_ was handled.

All scoped variables in request, view,
session and application scope.

If the error happens during the execution of
the view declaration language page (VDL)

The physical file being traversed at the time
the _Exception_ was thrown, such as _/user.xhtml_

The line number within that physical file at
the time the _Exception_ was thrown

Any available error message(s) from the VDL
page, such as: “The prefix "foz" for element "foz:bear" is not bound.”

The viewId at the time the
_ExceptionQueuedEvent_ was handled

If _Application.getProjectStage()_ returns
_ProjectStage.Development_ , the runtime must guarantee that the above
debug information is available to be included in any Facelet based error
page using the _<ui:include />_ with a _src_ attribute equal to the
string “ _jakarta.faces.error.xhtml_ ”.


[[a3300]]
=== FacesMessage

Each message queued within a _FacesContext_
is an instance of the _jakarta.faces.application.FacesMessage_ class. The
presence of one or more _FacesMessage_ instances on the _FacesContext_
indicates a failure of some kind during the lifecycle. In particular, a
validation or conversion failure is required to cause a _FacesMessage_
to be added to the _FacesContext_ . __

It offers the following constructors:

[width="100%",cols="100%",]
|===
a|
public FacesMessage();



public FacesMessage(String summary, String
detail);



public FacesMessage(Severity severity, String
summary, String detail);

|===

The following method signatures are supported
to retrieve and set the properties of the completed message:

[width="100%",cols="100%",]
|===
a|
public String getDetail();

public void setDetail(String detail);



public Severity getSeverity();

public void setSeverity(Severity severity);



public String getSummary();

public void setSummary(String summary);

|===

The message properties are defined as
follows:

_detail_ —Localized detail text for this
_FacesMessage_ (if any). This will generally be additional text that can
help the user understand the context of the problem being reported by
this _FacesMessage_ , and offer suggestions for correcting it.

_severity_ —A value defining how serious the
problem being reported by this _FacesMessage_ instance should be
considered. Four standard severity values ( _SEVERITY_INFO_ ,
_SEVERITY_WARN_ , _SEVERITY_ERROR_ , and _SEVERITY_FATAL_ ) are defined
as a typesafe enum in the _FacesMessage_ class.

_summary_ —Localized summary text for this
_FacesMessage_ . This is normally a relatively short message that
concisely describes the nature of the problem being reported by this
_FacesMessage_ .


=== ResponseStream

_ResponseStream_ is an abstract class
representing a binary output stream for the current response. It has
exactly the same method signatures as the _java.io.OutputStream_ class.


[[a3324]]
=== ResponseWriter

_ResponseWriter_ is an abstract class
representing a character output stream for the current response. A
_ResponseWriter_ instance is obtained via a factory method on
_RenderKit._ Please see <<RenderingModel.adoc#a4223,See RenderKit>>”. It
supports both low-level and high level APIs for writing character based
information

[width="100%",cols="100%",]
|===
a|
public void close() throws IOException;



public void flush() throws IOException;



public void write(char c[]) throws
IOException;



public void write(char c[], int off, int len)
throws IOException;



public void write(int c) throws IOException;



public void write(String s) throws
IOException;



public void write(String s, int off, int len)
throws IOException;

|===

The _ResponseWriter_ class extends
_java.io.Writer_ , and therefore inherits these method signatures for
low-level output. The _close()_ method flushes the underlying output
writer, and causes any further attempts to output characters to throw an
_IOException_ . The _flush_ method flushes any buffered information to
the underlying output writer, and commits the response. The _write_
methods write raw characters directly to the output writer.

[width="100%",cols="100%",]
|===
a|
public abstract String getContentType();

public abstract String
getCharacterEncoding();

|===

Return the content type or character encoding
used to create this ResponseWriter.

[width="100%",cols="100%",]
|===
a|
public void startCDATA();

public void endCDATA();

|===

Start and end an XML CDATA Section..

[width="100%",cols="100%",]
|===
a|
public void startDocument() throws
IOException;

public void endDocument() throws IOException;

|===

Write appropriate characters at the beginning
( _startDocument_ ) or end ( _endDocument_ ) of the current response.

[width="100%",cols="100%",]
|===
|public void startElement(String name,
UIComponent componentForElement) throws IOException;
|===

Write the beginning of a markup element (the
_<_ character followed by the element name), which causes the
_ResponseWriter_ implementation to note internally that the element is
open. This can be followed by zero or more calls to _writeAttribute_ or
_writeURIAttribute_ to append an attribute name and value to the
currently open element. The element will be closed (i.e. the trailing
_>_ added) on any subsequent call to _startElement_ (), _writeComment_
(), _writeText_ (), _endDocument_ (), _close()_ , _flush()_ , or
_write()_ . The _componentForElement_ parameter tells the
_ResponseWriter_ which _UIComponent_ this element corresponds to, if
any. This parameter may be null to indicate that the element has no
corresponding component. The presence of this parameter allows tools to
provide their own implementation of _ResponseWriter_ to allow the design
time environment to know which component corresponds to which piece of
markup.

[width="100%",cols="100%",]
|===
|public void endElement(String name) throws
IOException;
|===

Write a closing for the specified element,
closing any currently opened element first if necessary.

[width="100%",cols="100%",]
|===
|public void writeComment(Object comment)
throws IOException;
|===

Write a comment string wrapped in appropriate
comment delimiters, after converting the comment object to a _String_
first. Any currently opened element is closed first.

[width="100%",cols="100%",]
|===
a|
public void writeAttribute(String name,
Object value, String componentPropertyName) throws IOException;



public void writeURIAttribute(String name,
Object value, String componentPropertyName) throws IOException;

|===

These methods add an attribute name/value
pair to an element that was opened with a previous call to
_startElement()_ , throwing an exception if there is no currently open
element. The _writeAttribute()_ method causes character encoding to be
performed in the same manner as that performed by the _writeText()_
methods. The _writeURIAttribute()_ method assumes that the attribute
value is a URI, and performs URI encoding (such as _%_ encoding for
HTML). The _componentPropertyName_ , if present, denotes the property on
the associated _UIComponent_ for this element, to which this attribute
corresponds. The _componentPropertyName_ parameter may be null to
indicate that this attribute has no corresponding property.

[width="100%",cols="100%",]
|===
a|
public void writeText(Object text, String
property) throws IOException;



public void writeText(char text[], int off,
int len) throws IOException;

|===

Write text (converting from _Object_ to
_String_ first, if necessary), performing appropriate character encoding
and escaping. Any currently open element created by a call to
_startElement_ is closed first.

[width="100%",cols="100%",]
|===
|public abstract ResponseWriter
cloneWithWriter(Writer writer);
|===

Creates a new instance of this
_ResponseWriter_ , using a different _Writer_ .


[[a3366]]
=== FacesContextFactory

[P1-start-facesContextFactory]A single
instance of _jakarta.faces.context.FacesContextFactory_ must be made
available to each JSF-based web application running in a servlet or
portlet container.[P1-end] This class is primarily of use by JSF
implementors—applications will not generally call it directly. The
factory instance can be acquired, by JSF implementations or by
application code, by executing:

[width="100%",cols="100%",]
|===
a|
FacesContextFactory factory =

(FacesContextFactory)

FactoryFinder.getFactory(FactoryFinder.FACES_CONTEXT_FACTORY);

|===

pThe _FacesContextFactory_ implementation
class provides the following method signature to create (or recycle from
a pool) a _FacesContext_ instance:

[width="100%",cols="100%",]
|===
|public FacesContext getFacesContext(Object
context, Object request, Object response, Lifecycle lifecycle);
|===

Create (if necessary) and return a
_FacesContext_ instance that has been configured based on the specified
parameters. In a servlet environment, the first argument is a
_ServletContext_ , the second a _ServletRequest_ and the third a
_ServletResponse_ .


[[a3375]]
=== ExceptionHandlerFactory

[P1-start-exceptionHandlerFactory]A single
instance of _jakarta.faces.context.ExceptionHandlerFactory_ must be made
available to each JSF-based web application running in a servlet or
portlet container.[P1-end] The factory instance can be acquired, by JSF
implementations or by application code, by executing:

[width="100%",cols="100%",]
|===
a|
ExceptionHandlerFactory factory =

(ExceptionHandlerFactory)

FactoryFinder.getFactory(FactoryFinder.EXCEPTION_HANDLER_FACTORY);

|===

The _ExceptionHandlerFactory_ implementation
class provides the following method signature to create an
_ExceptionHandler_ instance:

[width="100%",cols="100%",]
|===
|public ExceptionHandler
getExceptionHandler(FacesContext currentContext);
|===

Create and return a _ExceptionHandler_
instance that has been configured based on the specified parameters.


[[a3384]]
=== ExternalContextFactory

[P1-start-externalContextFactory]A single
instance of _jakarta.faces.context.ExternalContextFactory_ must be made
available to each JSF-based web application running in a servlet or
portlet container.[P1-end] This class is primarily of use by JSF
implementors—applications will not generally call it directly. The
factory instance can be acquired, by JSF implementations or by
application code, by executing:

[width="100%",cols="100%",]
|===
a|
ExternalContextFactory factory =

(ExternalContextFactory)

FactoryFinder.getFactory(FactoryFinder.EXTERNAL_CONTEXT_FACTORY);

|===

pThe _ExternalContextFactory_ implementation
class provides the following method signature to create (or recycle from
a pool) a _FacesContext_ instance:

[width="100%",cols="100%",]
|===
|public ExternalContext
getExternalContext(Object context, Object request, Object response);
|===

Create (if necessary) and return an
_ExternalContext_ instance that has been configured based on the
specified parameters. In a servlet environment, the first argument is a
_ServletContext_ , the second a _ServletRequest_ and the third a
_ServletResponse_ .






