== Preface

This is the Jakarta Server Faces 3.0 (JSF 3.0) specification.

=== Changes between 3.0 and 2.3


=== Backward Compatibility with Previous Versions

JSF 3.0 has a breaking change due to the namespace change from  `javax.faces` to `jakarta.faces`.

=== Related Technologies

[[a173]]
=== Other Jakarta Platform Specifications

JSF is based on the following Jakarta specifications:

Jakarta Server Pages Specification, version 3.0
(JSP), including Expression Language 4.0
<https://github.com/eclipse-ee4j/jsp-api/>

Jakarta Expression Language 4.0
<https://github.com/eclipse-ee4j/el-ri> (optional)

Jakarta Servlet Specification, version 5.0
(Servlet) <https://github.com/eclipse-ee4j/servlet-api>


Contexts and Dependency Injection for Java 2.0
<http://jcp.org/en/jsr/detail?id=365>


JavaBeans™ Specification, version 1.0.1
<http://www.oracle.com/technetwork/java/javase/documentation/spec-136004.html>

JavaServer Pages™ Standard Tag Library, version
1.2 (JSTL) <http://jcp.org/en/jsr/detail?id=52>

Jakarta WebSocket, version 2.0
<https://github.com/eclipse-ee4j/websocket-api>

Jakarta JSON Processing, version 2.0
<https://github.com/eclipse-ee4j/jsonp>

Therefore, a JSF container must support all of
the above specifications. This requirement allows faces applications to
be portable across a variety of JSF implementations.

In addition, JSF is designed to work
synergistically with other web-related Java APIs, including:

Portlet Specification, 1.0 JSR-168
<http://jcp.org/en/jsr/detail?id=168>

Portlet Specification, 2.0 JSR-286
<http://jcp.org/en/jsr/detail?id=286>

Portlet Specification, 3.0 JSR-286
<http://jcp.org/en/jsr/detail?id=362>

JSF Portlet Bridge Specification, JSR-301
<http://jcp.org/en/jsr/detail?id=301>

=== Related Documents and Specifications

The following documents and specifications of
the World Wide Web Consortium will be of interest to JSF implementors,
as well as developers of applications and components based on Jakarta Server
Faces.

Hypertext Markup Language (HTML), version 4.01
<http://www.w3.org/TR/html4/>

Extensible HyperText Markup Language (XHTML),
version 1.0 <http://www.w3.org/TR/xhtml1>

Extensible Markup Language (XML), version 1.0
(Second Edition) <http://www.w3.org/TR/REC-xml>

The class and method Javadoc documentation for
the classes and interfaces in _javax.faces_ (and its subpackages) are
incorporated by reference as requirements of this Specification.

The JSP and Facelet tag library for the
HTML_BASIC standard RenderKit is specified in the VDLDocs and
incorporated by reference in this Specification.

=== Terminology

The key words MUST, MUST NOT, REQUIRED, SHALL,
SHALL NOT, SHOULD, SHOULD NOT, RECOMMENDED, MAY, and OPTIONAL in this
document are to be interpreted as described in

Key words for use in RFCs to Indicate
Requirement Levels (RFC 2119)
<http://www.rfc-editor.org/rfc/rfc2119.txt>

=== Providing Feedback

We welcome any and all feedback about this
specification. Please email your comments to
<faces-dev@eclipse.org>.

Please note that, due to the volume of feedback
that we receive, you will not normally receive a reply from an engineer.
However, each and every comment is read, evaluated, and archived by the
specification team.

=== Acknowledgements

The authors would like to thank the original JCP JSR-372 Expert Group and Contributors.

Frank Caputo

Cagatay Civici

Ken Fyten

Neil Griffin

Josh Juneau

Brian Leatham

Kito Mann

Michael Müller

Paul Nicolucci

Bauke Scholtz

Arjan Tijms

Leonardo Uribe

The editors would like to recognize the
following individuals who have contributed to the success of Jakarta Server
Faces over the years.

[width="100%",cols="50%,50%",]
|===
|Dan Allen |Thomas
Andraschko

|Thomas Asel |Jennifer
Ball

|Lincoln Baxter III
|Hans Bergsten

|Shawn Bayern |Joseph
Berkovitz

|Dennis Byrne |Pete
Carapetyan

|Ryan DeLaplante
|Keith Donald

|Jim Driscoll
|Hanspeter Duennenberger

|Ken Finnigan |Amy
Fowler

|Mike Freedman |David
Geary

|Manfred Geiler |Ted
Goddard

|Juan Gonzalez |Jeremy
Grelle

|Rick Hightower |Jacob
Hookom

|Justyna Horwat
|Alexander Jesse

|Max Katz |Roger Keays

|Gavin King |Roger
Kitain

|Eric Lazarus |Jason
Lee

|Felipe Leme |Cody
Lerum

|Alberto Lemos |Ryan
Lubke

|Barbara Louis |Martin
Marinschek

|Kumar Mettu |Craig
McClanahan

|Pete Muir |Bernd
Müller

|Michael Müller |Hans
Muller

|Brendan Murray
|Michael Nash

|Imre Osswald |Joe
Ottinger

|Ken Paulsen |Dhiru
Pandey

|Raj Premkumar |Werner
Punz

|Matt Raible |Hazem
Saleh

|Andy Schwartz |Yara
Senger

|Stan Silvert |Vernon
Singleton

|Bernhard Slominski
|Alexander Smirnov

|Thomas Spiegel |Kyle
Stiemann

|James Strachan
|Jayashri Visvanathan

|Ana von Klopp
|Matthias Wessendorf

|Adam Winer |Mike
Youngstrom

|John Zukowski |
|===
