type=page
status=published
title=Appendix A: Frequently Asked Questions
next=rebuild.html
prev=debug.html
~~~~~~
include::attributes.conf[]
Appendix A: Frequently Asked Questions
======================================

[[GBFYD]]


[[a-frequently-asked-questions]]
A Frequently Asked Questions
----------------------------

This appendix contains the following questions.

* link:#GBFYQ[Where do I start to debug a test failure?]
* link:#GBFYR[How do I restart a crashed test run?]
* link:#GBFWU[What would cause tests be added to the exclude list?]

[[GBFYQ]][[a.1-where-do-i-start-to-debug-a-test-failure]]

A.1 Where do I start to debug a test failure?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TBD 

[[GBFYR]][[a.2-how-do-i-restart-a-crashed-test-run]]

A.2 How do I restart a crashed test run?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

TBD

[[GBFWU]][[a.3-what-would-cause-tests-be-added-to-the-exclude-list]]

A.3 What would cause tests be added to the exclude list?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The exclude file (+{excludeListFileName}+) contains all tests that are not
required to be run. The following is a list of reasons for a test to be
included in the Exclude List:

* An error in a Compatible Implementation that does not allow the test to
execute properly has been discovered.
* An error in the specification that was used as the basis of the test
has been discovered.
* An error in the test has been discovered.
